// Code generated by ent, DO NOT EDIT.

package metricssnapshot

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the metricssnapshot type in the database.
	Label = "metrics_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPeriod holds the string denoting the period field in the database.
	FieldPeriod = "period"
	// FieldPeriodStart holds the string denoting the period_start field in the database.
	FieldPeriodStart = "period_start"
	// FieldPeriodEnd holds the string denoting the period_end field in the database.
	FieldPeriodEnd = "period_end"
	// FieldAlertsTotal holds the string denoting the alerts_total field in the database.
	FieldAlertsTotal = "alerts_total"
	// FieldAlertsNotified holds the string denoting the alerts_notified field in the database.
	FieldAlertsNotified = "alerts_notified"
	// FieldAlertsUnrouted holds the string denoting the alerts_unrouted field in the database.
	FieldAlertsUnrouted = "alerts_unrouted"
	// FieldNoiseRate holds the string denoting the noise_rate field in the database.
	FieldNoiseRate = "noise_rate"
	// FieldIncidentsTotal holds the string denoting the incidents_total field in the database.
	FieldIncidentsTotal = "incidents_total"
	// FieldIncidentsResolved holds the string denoting the incidents_resolved field in the database.
	FieldIncidentsResolved = "incidents_resolved"
	// FieldMttaSeconds holds the string denoting the mtta_seconds field in the database.
	FieldMttaSeconds = "mtta_seconds"
	// FieldMttrSeconds holds the string denoting the mttr_seconds field in the database.
	FieldMttrSeconds = "mttr_seconds"
	// FieldBySeverity holds the string denoting the by_severity field in the database.
	FieldBySeverity = "by_severity"
	// FieldByStatus holds the string denoting the by_status field in the database.
	FieldByStatus = "by_status"
	// FieldPostmortemsTotal holds the string denoting the postmortems_total field in the database.
	FieldPostmortemsTotal = "postmortems_total"
	// FieldPostmortemsPublished holds the string denoting the postmortems_published field in the database.
	FieldPostmortemsPublished = "postmortems_published"
	// FieldCompletionRate holds the string denoting the completion_rate field in the database.
	FieldCompletionRate = "completion_rate"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTeam holds the string denoting the team edge name in mutations.
	EdgeTeam = "team"
	// Table holds the table name of the metricssnapshot in the database.
	Table = "metrics_snapshots"
	// TeamTable is the table that holds the team relation/edge.
	TeamTable = "metrics_snapshots"
	// TeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamInverseTable = "teams"
	// TeamColumn is the table column denoting the team relation/edge.
	TeamColumn = "team_metrics_snapshots"
)

// Columns holds all SQL columns for metricssnapshot fields.
var Columns = []string{
	FieldID,
	FieldPeriod,
	FieldPeriodStart,
	FieldPeriodEnd,
	FieldAlertsTotal,
	FieldAlertsNotified,
	FieldAlertsUnrouted,
	FieldNoiseRate,
	FieldIncidentsTotal,
	FieldIncidentsResolved,
	FieldMttaSeconds,
	FieldMttrSeconds,
	FieldBySeverity,
	FieldByStatus,
	FieldPostmortemsTotal,
	FieldPostmortemsPublished,
	FieldCompletionRate,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "metrics_snapshots"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"team_metrics_snapshots",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAlertsTotal holds the default value on creation for the "alerts_total" field.
	DefaultAlertsTotal int
	// DefaultAlertsNotified holds the default value on creation for the "alerts_notified" field.
	DefaultAlertsNotified int
	// DefaultAlertsUnrouted holds the default value on creation for the "alerts_unrouted" field.
	DefaultAlertsUnrouted int
	// DefaultNoiseRate holds the default value on creation for the "noise_rate" field.
	DefaultNoiseRate float64
	// DefaultIncidentsTotal holds the default value on creation for the "incidents_total" field.
	DefaultIncidentsTotal int
	// DefaultIncidentsResolved holds the default value on creation for the "incidents_resolved" field.
	DefaultIncidentsResolved int
	// DefaultMttaSeconds holds the default value on creation for the "mtta_seconds" field.
	DefaultMttaSeconds float64
	// DefaultMttrSeconds holds the default value on creation for the "mttr_seconds" field.
	DefaultMttrSeconds float64
	// DefaultPostmortemsTotal holds the default value on creation for the "postmortems_total" field.
	DefaultPostmortemsTotal int
	// DefaultPostmortemsPublished holds the default value on creation for the "postmortems_published" field.
	DefaultPostmortemsPublished int
	// DefaultCompletionRate holds the default value on creation for the "completion_rate" field.
	DefaultCompletionRate float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Period defines the type for the "period" enum field.
type Period string

// PeriodDaily is the default value of the Period enum.
const DefaultPeriod = PeriodDaily

// Period values.
const (
	PeriodHourly Period = "hourly"
	PeriodDaily  Period = "daily"
)

func (pe Period) String() string {
	return string(pe)
}

// PeriodValidator is a validator for the "period" field enum values. It is called by the builders before save.
func PeriodValidator(pe Period) error {
	switch pe {
	case PeriodHourly, PeriodDaily:
		return nil
	default:
		return fmt.Errorf("metricssnapshot: invalid enum value for period field: %q", pe)
	}
}

// OrderOption defines the ordering options for the MetricsSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPeriod orders the results by the period field.
func ByPeriod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriod, opts...).ToFunc()
}

// ByPeriodStart orders the results by the period_start field.
func ByPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodStart, opts...).ToFunc()
}

// ByPeriodEnd orders the results by the period_end field.
func ByPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodEnd, opts...).ToFunc()
}

// ByAlertsTotal orders the results by the alerts_total field.
func ByAlertsTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertsTotal, opts...).ToFunc()
}

// ByAlertsNotified orders the results by the alerts_notified field.
func ByAlertsNotified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertsNotified, opts...).ToFunc()
}

// ByAlertsUnrouted orders the results by the alerts_unrouted field.
func ByAlertsUnrouted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertsUnrouted, opts...).ToFunc()
}

// ByNoiseRate orders the results by the noise_rate field.
func ByNoiseRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNoiseRate, opts...).ToFunc()
}

// ByIncidentsTotal orders the results by the incidents_total field.
func ByIncidentsTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIncidentsTotal, opts...).ToFunc()
}

// ByIncidentsResolved orders the results by the incidents_resolved field.
func ByIncidentsResolved(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIncidentsResolved, opts...).ToFunc()
}

// ByMttaSeconds orders the results by the mtta_seconds field.
func ByMttaSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMttaSeconds, opts...).ToFunc()
}

// ByMttrSeconds orders the results by the mttr_seconds field.
func ByMttrSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMttrSeconds, opts...).ToFunc()
}

// ByPostmortemsTotal orders the results by the postmortems_total field.
func ByPostmortemsTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostmortemsTotal, opts...).ToFunc()
}

// ByPostmortemsPublished orders the results by the postmortems_published field.
func ByPostmortemsPublished(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostmortemsPublished, opts...).ToFunc()
}

// ByCompletionRate orders the results by the completion_rate field.
func ByCompletionRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionRate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTeamField orders the results by team field.
func ByTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamStep(), sql.OrderByField(field, opts...))
	}
}
func newTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
	)
}
