// Code generated by ent, DO NOT EDIT.

package metricssnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kevin/vigil/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldID, id))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldPeriodEnd, v))
}

// AlertsTotal applies equality check predicate on the "alerts_total" field. It's identical to AlertsTotalEQ.
func AlertsTotal(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldAlertsTotal, v))
}

// AlertsNotified applies equality check predicate on the "alerts_notified" field. It's identical to AlertsNotifiedEQ.
func AlertsNotified(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldAlertsNotified, v))
}

// AlertsUnrouted applies equality check predicate on the "alerts_unrouted" field. It's identical to AlertsUnroutedEQ.
func AlertsUnrouted(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldAlertsUnrouted, v))
}

// NoiseRate applies equality check predicate on the "noise_rate" field. It's identical to NoiseRateEQ.
func NoiseRate(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldNoiseRate, v))
}

// IncidentsTotal applies equality check predicate on the "incidents_total" field. It's identical to IncidentsTotalEQ.
func IncidentsTotal(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldIncidentsTotal, v))
}

// IncidentsResolved applies equality check predicate on the "incidents_resolved" field. It's identical to IncidentsResolvedEQ.
func IncidentsResolved(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldIncidentsResolved, v))
}

// MttaSeconds applies equality check predicate on the "mtta_seconds" field. It's identical to MttaSecondsEQ.
func MttaSeconds(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldMttaSeconds, v))
}

// MttrSeconds applies equality check predicate on the "mttr_seconds" field. It's identical to MttrSecondsEQ.
func MttrSeconds(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldMttrSeconds, v))
}

// PostmortemsTotal applies equality check predicate on the "postmortems_total" field. It's identical to PostmortemsTotalEQ.
func PostmortemsTotal(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldPostmortemsTotal, v))
}

// PostmortemsPublished applies equality check predicate on the "postmortems_published" field. It's identical to PostmortemsPublishedEQ.
func PostmortemsPublished(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldPostmortemsPublished, v))
}

// CompletionRate applies equality check predicate on the "completion_rate" field. It's identical to CompletionRateEQ.
func CompletionRate(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldCompletionRate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// PeriodEQ applies the EQ predicate on the "period" field.
func PeriodEQ(v Period) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldPeriod, v))
}

// PeriodNEQ applies the NEQ predicate on the "period" field.
func PeriodNEQ(v Period) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldPeriod, v))
}

// PeriodIn applies the In predicate on the "period" field.
func PeriodIn(vs ...Period) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldPeriod, vs...))
}

// PeriodNotIn applies the NotIn predicate on the "period" field.
func PeriodNotIn(vs ...Period) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldPeriod, vs...))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldPeriodEnd, v))
}

// AlertsTotalEQ applies the EQ predicate on the "alerts_total" field.
func AlertsTotalEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldAlertsTotal, v))
}

// AlertsTotalNEQ applies the NEQ predicate on the "alerts_total" field.
func AlertsTotalNEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldAlertsTotal, v))
}

// AlertsTotalIn applies the In predicate on the "alerts_total" field.
func AlertsTotalIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldAlertsTotal, vs...))
}

// AlertsTotalNotIn applies the NotIn predicate on the "alerts_total" field.
func AlertsTotalNotIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldAlertsTotal, vs...))
}

// AlertsTotalGT applies the GT predicate on the "alerts_total" field.
func AlertsTotalGT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldAlertsTotal, v))
}

// AlertsTotalGTE applies the GTE predicate on the "alerts_total" field.
func AlertsTotalGTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldAlertsTotal, v))
}

// AlertsTotalLT applies the LT predicate on the "alerts_total" field.
func AlertsTotalLT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldAlertsTotal, v))
}

// AlertsTotalLTE applies the LTE predicate on the "alerts_total" field.
func AlertsTotalLTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldAlertsTotal, v))
}

// AlertsNotifiedEQ applies the EQ predicate on the "alerts_notified" field.
func AlertsNotifiedEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldAlertsNotified, v))
}

// AlertsNotifiedNEQ applies the NEQ predicate on the "alerts_notified" field.
func AlertsNotifiedNEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldAlertsNotified, v))
}

// AlertsNotifiedIn applies the In predicate on the "alerts_notified" field.
func AlertsNotifiedIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldAlertsNotified, vs...))
}

// AlertsNotifiedNotIn applies the NotIn predicate on the "alerts_notified" field.
func AlertsNotifiedNotIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldAlertsNotified, vs...))
}

// AlertsNotifiedGT applies the GT predicate on the "alerts_notified" field.
func AlertsNotifiedGT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldAlertsNotified, v))
}

// AlertsNotifiedGTE applies the GTE predicate on the "alerts_notified" field.
func AlertsNotifiedGTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldAlertsNotified, v))
}

// AlertsNotifiedLT applies the LT predicate on the "alerts_notified" field.
func AlertsNotifiedLT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldAlertsNotified, v))
}

// AlertsNotifiedLTE applies the LTE predicate on the "alerts_notified" field.
func AlertsNotifiedLTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldAlertsNotified, v))
}

// AlertsUnroutedEQ applies the EQ predicate on the "alerts_unrouted" field.
func AlertsUnroutedEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldAlertsUnrouted, v))
}

// AlertsUnroutedNEQ applies the NEQ predicate on the "alerts_unrouted" field.
func AlertsUnroutedNEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldAlertsUnrouted, v))
}

// AlertsUnroutedIn applies the In predicate on the "alerts_unrouted" field.
func AlertsUnroutedIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldAlertsUnrouted, vs...))
}

// AlertsUnroutedNotIn applies the NotIn predicate on the "alerts_unrouted" field.
func AlertsUnroutedNotIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldAlertsUnrouted, vs...))
}

// AlertsUnroutedGT applies the GT predicate on the "alerts_unrouted" field.
func AlertsUnroutedGT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldAlertsUnrouted, v))
}

// AlertsUnroutedGTE applies the GTE predicate on the "alerts_unrouted" field.
func AlertsUnroutedGTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldAlertsUnrouted, v))
}

// AlertsUnroutedLT applies the LT predicate on the "alerts_unrouted" field.
func AlertsUnroutedLT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldAlertsUnrouted, v))
}

// AlertsUnroutedLTE applies the LTE predicate on the "alerts_unrouted" field.
func AlertsUnroutedLTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldAlertsUnrouted, v))
}

// NoiseRateEQ applies the EQ predicate on the "noise_rate" field.
func NoiseRateEQ(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldNoiseRate, v))
}

// NoiseRateNEQ applies the NEQ predicate on the "noise_rate" field.
func NoiseRateNEQ(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldNoiseRate, v))
}

// NoiseRateIn applies the In predicate on the "noise_rate" field.
func NoiseRateIn(vs ...float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldNoiseRate, vs...))
}

// NoiseRateNotIn applies the NotIn predicate on the "noise_rate" field.
func NoiseRateNotIn(vs ...float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldNoiseRate, vs...))
}

// NoiseRateGT applies the GT predicate on the "noise_rate" field.
func NoiseRateGT(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldNoiseRate, v))
}

// NoiseRateGTE applies the GTE predicate on the "noise_rate" field.
func NoiseRateGTE(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldNoiseRate, v))
}

// NoiseRateLT applies the LT predicate on the "noise_rate" field.
func NoiseRateLT(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldNoiseRate, v))
}

// NoiseRateLTE applies the LTE predicate on the "noise_rate" field.
func NoiseRateLTE(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldNoiseRate, v))
}

// IncidentsTotalEQ applies the EQ predicate on the "incidents_total" field.
func IncidentsTotalEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldIncidentsTotal, v))
}

// IncidentsTotalNEQ applies the NEQ predicate on the "incidents_total" field.
func IncidentsTotalNEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldIncidentsTotal, v))
}

// IncidentsTotalIn applies the In predicate on the "incidents_total" field.
func IncidentsTotalIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldIncidentsTotal, vs...))
}

// IncidentsTotalNotIn applies the NotIn predicate on the "incidents_total" field.
func IncidentsTotalNotIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldIncidentsTotal, vs...))
}

// IncidentsTotalGT applies the GT predicate on the "incidents_total" field.
func IncidentsTotalGT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldIncidentsTotal, v))
}

// IncidentsTotalGTE applies the GTE predicate on the "incidents_total" field.
func IncidentsTotalGTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldIncidentsTotal, v))
}

// IncidentsTotalLT applies the LT predicate on the "incidents_total" field.
func IncidentsTotalLT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldIncidentsTotal, v))
}

// IncidentsTotalLTE applies the LTE predicate on the "incidents_total" field.
func IncidentsTotalLTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldIncidentsTotal, v))
}

// IncidentsResolvedEQ applies the EQ predicate on the "incidents_resolved" field.
func IncidentsResolvedEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldIncidentsResolved, v))
}

// IncidentsResolvedNEQ applies the NEQ predicate on the "incidents_resolved" field.
func IncidentsResolvedNEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldIncidentsResolved, v))
}

// IncidentsResolvedIn applies the In predicate on the "incidents_resolved" field.
func IncidentsResolvedIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldIncidentsResolved, vs...))
}

// IncidentsResolvedNotIn applies the NotIn predicate on the "incidents_resolved" field.
func IncidentsResolvedNotIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldIncidentsResolved, vs...))
}

// IncidentsResolvedGT applies the GT predicate on the "incidents_resolved" field.
func IncidentsResolvedGT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldIncidentsResolved, v))
}

// IncidentsResolvedGTE applies the GTE predicate on the "incidents_resolved" field.
func IncidentsResolvedGTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldIncidentsResolved, v))
}

// IncidentsResolvedLT applies the LT predicate on the "incidents_resolved" field.
func IncidentsResolvedLT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldIncidentsResolved, v))
}

// IncidentsResolvedLTE applies the LTE predicate on the "incidents_resolved" field.
func IncidentsResolvedLTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldIncidentsResolved, v))
}

// MttaSecondsEQ applies the EQ predicate on the "mtta_seconds" field.
func MttaSecondsEQ(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldMttaSeconds, v))
}

// MttaSecondsNEQ applies the NEQ predicate on the "mtta_seconds" field.
func MttaSecondsNEQ(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldMttaSeconds, v))
}

// MttaSecondsIn applies the In predicate on the "mtta_seconds" field.
func MttaSecondsIn(vs ...float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldMttaSeconds, vs...))
}

// MttaSecondsNotIn applies the NotIn predicate on the "mtta_seconds" field.
func MttaSecondsNotIn(vs ...float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldMttaSeconds, vs...))
}

// MttaSecondsGT applies the GT predicate on the "mtta_seconds" field.
func MttaSecondsGT(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldMttaSeconds, v))
}

// MttaSecondsGTE applies the GTE predicate on the "mtta_seconds" field.
func MttaSecondsGTE(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldMttaSeconds, v))
}

// MttaSecondsLT applies the LT predicate on the "mtta_seconds" field.
func MttaSecondsLT(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldMttaSeconds, v))
}

// MttaSecondsLTE applies the LTE predicate on the "mtta_seconds" field.
func MttaSecondsLTE(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldMttaSeconds, v))
}

// MttrSecondsEQ applies the EQ predicate on the "mttr_seconds" field.
func MttrSecondsEQ(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldMttrSeconds, v))
}

// MttrSecondsNEQ applies the NEQ predicate on the "mttr_seconds" field.
func MttrSecondsNEQ(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldMttrSeconds, v))
}

// MttrSecondsIn applies the In predicate on the "mttr_seconds" field.
func MttrSecondsIn(vs ...float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldMttrSeconds, vs...))
}

// MttrSecondsNotIn applies the NotIn predicate on the "mttr_seconds" field.
func MttrSecondsNotIn(vs ...float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldMttrSeconds, vs...))
}

// MttrSecondsGT applies the GT predicate on the "mttr_seconds" field.
func MttrSecondsGT(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldMttrSeconds, v))
}

// MttrSecondsGTE applies the GTE predicate on the "mttr_seconds" field.
func MttrSecondsGTE(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldMttrSeconds, v))
}

// MttrSecondsLT applies the LT predicate on the "mttr_seconds" field.
func MttrSecondsLT(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldMttrSeconds, v))
}

// MttrSecondsLTE applies the LTE predicate on the "mttr_seconds" field.
func MttrSecondsLTE(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldMttrSeconds, v))
}

// BySeverityIsNil applies the IsNil predicate on the "by_severity" field.
func BySeverityIsNil() predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIsNull(FieldBySeverity))
}

// BySeverityNotNil applies the NotNil predicate on the "by_severity" field.
func BySeverityNotNil() predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotNull(FieldBySeverity))
}

// ByStatusIsNil applies the IsNil predicate on the "by_status" field.
func ByStatusIsNil() predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIsNull(FieldByStatus))
}

// ByStatusNotNil applies the NotNil predicate on the "by_status" field.
func ByStatusNotNil() predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotNull(FieldByStatus))
}

// PostmortemsTotalEQ applies the EQ predicate on the "postmortems_total" field.
func PostmortemsTotalEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldPostmortemsTotal, v))
}

// PostmortemsTotalNEQ applies the NEQ predicate on the "postmortems_total" field.
func PostmortemsTotalNEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldPostmortemsTotal, v))
}

// PostmortemsTotalIn applies the In predicate on the "postmortems_total" field.
func PostmortemsTotalIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldPostmortemsTotal, vs...))
}

// PostmortemsTotalNotIn applies the NotIn predicate on the "postmortems_total" field.
func PostmortemsTotalNotIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldPostmortemsTotal, vs...))
}

// PostmortemsTotalGT applies the GT predicate on the "postmortems_total" field.
func PostmortemsTotalGT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldPostmortemsTotal, v))
}

// PostmortemsTotalGTE applies the GTE predicate on the "postmortems_total" field.
func PostmortemsTotalGTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldPostmortemsTotal, v))
}

// PostmortemsTotalLT applies the LT predicate on the "postmortems_total" field.
func PostmortemsTotalLT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldPostmortemsTotal, v))
}

// PostmortemsTotalLTE applies the LTE predicate on the "postmortems_total" field.
func PostmortemsTotalLTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldPostmortemsTotal, v))
}

// PostmortemsPublishedEQ applies the EQ predicate on the "postmortems_published" field.
func PostmortemsPublishedEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldPostmortemsPublished, v))
}

// PostmortemsPublishedNEQ applies the NEQ predicate on the "postmortems_published" field.
func PostmortemsPublishedNEQ(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldPostmortemsPublished, v))
}

// PostmortemsPublishedIn applies the In predicate on the "postmortems_published" field.
func PostmortemsPublishedIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldPostmortemsPublished, vs...))
}

// PostmortemsPublishedNotIn applies the NotIn predicate on the "postmortems_published" field.
func PostmortemsPublishedNotIn(vs ...int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldPostmortemsPublished, vs...))
}

// PostmortemsPublishedGT applies the GT predicate on the "postmortems_published" field.
func PostmortemsPublishedGT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldPostmortemsPublished, v))
}

// PostmortemsPublishedGTE applies the GTE predicate on the "postmortems_published" field.
func PostmortemsPublishedGTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldPostmortemsPublished, v))
}

// PostmortemsPublishedLT applies the LT predicate on the "postmortems_published" field.
func PostmortemsPublishedLT(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldPostmortemsPublished, v))
}

// PostmortemsPublishedLTE applies the LTE predicate on the "postmortems_published" field.
func PostmortemsPublishedLTE(v int) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldPostmortemsPublished, v))
}

// CompletionRateEQ applies the EQ predicate on the "completion_rate" field.
func CompletionRateEQ(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldCompletionRate, v))
}

// CompletionRateNEQ applies the NEQ predicate on the "completion_rate" field.
func CompletionRateNEQ(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldCompletionRate, v))
}

// CompletionRateIn applies the In predicate on the "completion_rate" field.
func CompletionRateIn(vs ...float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldCompletionRate, vs...))
}

// CompletionRateNotIn applies the NotIn predicate on the "completion_rate" field.
func CompletionRateNotIn(vs ...float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldCompletionRate, vs...))
}

// CompletionRateGT applies the GT predicate on the "completion_rate" field.
func CompletionRateGT(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldCompletionRate, v))
}

// CompletionRateGTE applies the GTE predicate on the "completion_rate" field.
func CompletionRateGTE(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldCompletionRate, v))
}

// CompletionRateLT applies the LT predicate on the "completion_rate" field.
func CompletionRateLT(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldCompletionRate, v))
}

// CompletionRateLTE applies the LTE predicate on the "completion_rate" field.
func CompletionRateLTE(v float64) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldCompletionRate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MetricsSnapshot) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MetricsSnapshot) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MetricsSnapshot) predicate.MetricsSnapshot {
	return predicate.MetricsSnapshot(sql.NotPredicates(p))
}
