-- 0002_baseline.sql
-- Schema baseline 版本锚点（ENG-01：让迁移名实相符）。
--
-- 设计说明（重要）：
-- Vigil 采用「版本追踪 + ent auto-migrate」混合方案：
--   · schema_migrations 表追踪已应用版本（本文件 = 版本 0002_baseline）
--   · pre_*.sql 在 auto-migrate 前执行（如 pgvector 扩展安装）
--   · ent auto-migrate（migrate.Run 第 6 步）负责创建/同步全部 17 个实体表
--   · post_*.sql 在 auto-migrate 后执行（未来增量：数据回填/索引调优等）
--
-- 为什么本文件不含 CREATE TABLE：
--   ent schema（ent/schema/*.go → ent/migrate/schema.go）是 schema 的权威源。
--   运行时由 ent auto-migrate 创建/同步表，保证「代码与 schema 强一致」（编译期保障），
--   避免 SQL DDL 与 Go 代码双写漂移。
--
--   完整可 review 的 DDL 镜像见 internal/migrate/schema/baseline.sql
--   （由 cmd/genmigration 从 ent schema 生成，CI drift 检测保证同步，但不参与运行时 apply）。
--
-- 本文件存在的意义：
--   1. 在 schema_migrations 记录 baseline 版本，使版本链可追溯
--   2. 作为未来「纯 SQL 增量迁移」的挂载点（如需 hand-tuned SQL 调优时追加 0003_*.sql）
--   3. SELECT 1 保证幂等可重放（任何 PG 版本都能执行）
--
-- 为什么本版本【不提供 .down.sql】（migrate down 会显式拒绝逆向 0002_baseline）：
--   baseline 代表「全部 ent 实体表已由 auto-migrate 建好」这个锚点。逆向它意味着
--   drop 掉所有业务表 = 灾难性数据丢失，且这不是 ent 声明式 diff 能安全表达的操作。
--   ent 实体结构的回退【只能靠备份恢复】（scripts/restore.sh）——这正是 migrate down
--   诚实拒绝无 down 脚本的版本、而非静默跳过的原因。
SELECT 1;
