-- vigil:destructive
-- pre_0001_pgvector.down.sql —— 逆向 pre_0001_pgvector.sql（DROP pgvector 扩展）。
--
-- ★ 破坏性（标记 vigil:destructive）：
--   卸载 vector 扩展会连带删除所有 vector 类型的列/索引。Vigil 中
--   Incident.embedding（vector(1536)）等由 ent auto-migrate 创建的列依赖此扩展。
--   因此本 down 脚本用 RESTRICT（默认）语义：若仍有依赖对象存在，DROP 会失败——
--   这是刻意的防呆：不能在实体列还在时删扩展。
--
-- 正确的完整回退顺序应为：先用备份恢复实体结构（scripts/restore.sh），
-- 或先手工删除依赖 vector 的列，再执行本脚本删扩展。
--
-- 幂等：IF EXISTS 保证扩展不存在时不报错。
DROP EXTENSION IF EXISTS vector;
