// Code generated by ent, DO NOT EDIT.

package suppressionrule

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the suppressionrule type in the database.
	Label = "suppression_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldMatchLabels holds the string denoting the match_labels field in the database.
	FieldMatchLabels = "match_labels"
	// FieldTimeWindow holds the string denoting the time_window field in the database.
	FieldTimeWindow = "time_window"
	// FieldSeverityFilter holds the string denoting the severity_filter field in the database.
	FieldSeverityFilter = "severity_filter"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldReduceTo holds the string denoting the reduce_to field in the database.
	FieldReduceTo = "reduce_to"
	// FieldPreserveCritical holds the string denoting the preserve_critical field in the database.
	FieldPreserveCritical = "preserve_critical"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSourceInsightID holds the string denoting the source_insight_id field in the database.
	FieldSourceInsightID = "source_insight_id"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTeam holds the string denoting the team edge name in mutations.
	EdgeTeam = "team"
	// Table holds the table name of the suppressionrule in the database.
	Table = "suppression_rules"
	// TeamTable is the table that holds the team relation/edge.
	TeamTable = "suppression_rules"
	// TeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamInverseTable = "teams"
	// TeamColumn is the table column denoting the team relation/edge.
	TeamColumn = "team_suppression_rules"
)

// Columns holds all SQL columns for suppressionrule fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldKind,
	FieldMatchLabels,
	FieldTimeWindow,
	FieldSeverityFilter,
	FieldAction,
	FieldReduceTo,
	FieldPreserveCritical,
	FieldEnabled,
	FieldSource,
	FieldSourceInsightID,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "suppression_rules"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"team_suppression_rules",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPreserveCritical holds the default value on creation for the "preserve_critical" field.
	DefaultPreserveCritical bool
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Kind defines the type for the "kind" enum field.
type Kind string

// KindAdhoc is the default value of the Kind enum.
const DefaultKind = KindAdhoc

// Kind values.
const (
	KindAdhoc       Kind = "adhoc"
	KindMaintenance Kind = "maintenance"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindAdhoc, KindMaintenance:
		return nil
	default:
		return fmt.Errorf("suppressionrule: invalid enum value for kind field: %q", k)
	}
}

// Action defines the type for the "action" enum field.
type Action string

// ActionSuppress is the default value of the Action enum.
const DefaultAction = ActionSuppress

// Action values.
const (
	ActionSuppress       Action = "suppress"
	ActionReduceSeverity Action = "reduce_severity"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionSuppress, ActionReduceSeverity:
		return nil
	default:
		return fmt.Errorf("suppressionrule: invalid enum value for action field: %q", a)
	}
}

// Source defines the type for the "source" enum field.
type Source string

// SourceManual is the default value of the Source enum.
const DefaultSource = SourceManual

// Source values.
const (
	SourceManual Source = "manual"
	SourceAi     Source = "ai"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceManual, SourceAi:
		return nil
	default:
		return fmt.Errorf("suppressionrule: invalid enum value for source field: %q", s)
	}
}

// OrderOption defines the ordering options for the SuppressionRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByReduceTo orders the results by the reduce_to field.
func ByReduceTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReduceTo, opts...).ToFunc()
}

// ByPreserveCritical orders the results by the preserve_critical field.
func ByPreserveCritical(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreserveCritical, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySourceInsightID orders the results by the source_insight_id field.
func BySourceInsightID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceInsightID, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTeamField orders the results by team field.
func ByTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamStep(), sql.OrderByField(field, opts...))
	}
}
func newTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
	)
}
