// Code generated by ent, DO NOT EDIT.

package notificationtemplate

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the notificationtemplate type in the database.
	Label = "notification_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldFormat holds the string denoting the format field in the database.
	FieldFormat = "format"
	// FieldTitleTemplate holds the string denoting the title_template field in the database.
	FieldTitleTemplate = "title_template"
	// FieldBodyTemplate holds the string denoting the body_template field in the database.
	FieldBodyTemplate = "body_template"
	// FieldActions holds the string denoting the actions field in the database.
	FieldActions = "actions"
	// FieldBuiltin holds the string denoting the builtin field in the database.
	FieldBuiltin = "builtin"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTeam holds the string denoting the team edge name in mutations.
	EdgeTeam = "team"
	// Table holds the table name of the notificationtemplate in the database.
	Table = "notification_templates"
	// TeamTable is the table that holds the team relation/edge.
	TeamTable = "notification_templates"
	// TeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamInverseTable = "teams"
	// TeamColumn is the table column denoting the team relation/edge.
	TeamColumn = "team_notification_templates"
)

// Columns holds all SQL columns for notificationtemplate fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldChannel,
	FieldFormat,
	FieldTitleTemplate,
	FieldBodyTemplate,
	FieldActions,
	FieldBuiltin,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "notification_templates"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"team_notification_templates",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultBuiltin holds the default value on creation for the "builtin" field.
	DefaultBuiltin bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Channel defines the type for the "channel" enum field.
type Channel string

// Channel values.
const (
	ChannelIm      Channel = "im"
	ChannelEmail   Channel = "email"
	ChannelWebhook Channel = "webhook"
	ChannelPhone   Channel = "phone"
	ChannelSms     Channel = "sms"
)

func (c Channel) String() string {
	return string(c)
}

// ChannelValidator is a validator for the "channel" field enum values. It is called by the builders before save.
func ChannelValidator(c Channel) error {
	switch c {
	case ChannelIm, ChannelEmail, ChannelWebhook, ChannelPhone, ChannelSms:
		return nil
	default:
		return fmt.Errorf("notificationtemplate: invalid enum value for channel field: %q", c)
	}
}

// Format defines the type for the "format" enum field.
type Format string

// Format values.
const (
	FormatText            Format = "text"
	FormatInteractiveCard Format = "interactive_card"
)

func (f Format) String() string {
	return string(f)
}

// FormatValidator is a validator for the "format" field enum values. It is called by the builders before save.
func FormatValidator(f Format) error {
	switch f {
	case FormatText, FormatInteractiveCard:
		return nil
	default:
		return fmt.Errorf("notificationtemplate: invalid enum value for format field: %q", f)
	}
}

// OrderOption defines the ordering options for the NotificationTemplate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByFormat orders the results by the format field.
func ByFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormat, opts...).ToFunc()
}

// ByTitleTemplate orders the results by the title_template field.
func ByTitleTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleTemplate, opts...).ToFunc()
}

// ByBodyTemplate orders the results by the body_template field.
func ByBodyTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBodyTemplate, opts...).ToFunc()
}

// ByBuiltin orders the results by the builtin field.
func ByBuiltin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuiltin, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTeamField orders the results by team field.
func ByTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamStep(), sql.OrderByField(field, opts...))
	}
}
func newTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
	)
}
