// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AiInsightsColumns holds the columns for the "ai_insights" table.
	AiInsightsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "stage", Type: field.TypeEnum, Enums: []string{"triage", "diagnose", "postmortem", "copilot"}},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"dedup_suggestion", "severity_adjustment", "root_cause_hint", "similar_incident", "draft_summary", "postmortem_draft", "runbook_suggestion"}},
		{Name: "content", Type: field.TypeJSON},
		{Name: "confidence", Type: field.TypeFloat32, Default: 0},
		{Name: "evidence", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"suggested", "accepted", "rejected", "applied"}, Default: "suggested"},
		{Name: "resolved_by", Type: field.TypeInt, Nullable: true},
		{Name: "resolved_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "incident_ai_insights", Type: field.TypeInt, Nullable: true},
	}
	// AiInsightsTable holds the schema information for the "ai_insights" table.
	AiInsightsTable = &schema.Table{
		Name:       "ai_insights",
		Columns:    AiInsightsColumns,
		PrimaryKey: []*schema.Column{AiInsightsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ai_insights_incidents_ai_insights",
				Columns:    []*schema.Column{AiInsightsColumns[11]},
				RefColumns: []*schema.Column{IncidentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "aiinsight_incident_ai_insights",
				Unique:  false,
				Columns: []*schema.Column{AiInsightsColumns[11]},
			},
			{
				Name:    "aiinsight_stage",
				Unique:  false,
				Columns: []*schema.Column{AiInsightsColumns[1]},
			},
			{
				Name:    "aiinsight_status",
				Unique:  false,
				Columns: []*schema.Column{AiInsightsColumns[6]},
			},
		},
	}
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "prefix", Type: field.TypeString},
		{Name: "scope", Type: field.TypeJSON, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_api_keys", Type: field.TypeInt},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_token_hash",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[2]},
			},
			{
				Name:    "apikey_status",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[7]},
			},
		},
	}
	// ActionItemsColumns holds the columns for the "action_items" table.
	ActionItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "owner_id", Type: field.TypeString, Nullable: true},
		{Name: "due_date", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"open", "in_progress", "done"}, Default: "open"},
		{Name: "tracker_url", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "postmortem_action_items", Type: field.TypeInt, Nullable: true},
	}
	// ActionItemsTable holds the schema information for the "action_items" table.
	ActionItemsTable = &schema.Table{
		Name:       "action_items",
		Columns:    ActionItemsColumns,
		PrimaryKey: []*schema.Column{ActionItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "action_items_postmortems_action_items",
				Columns:    []*schema.Column{ActionItemsColumns[8]},
				RefColumns: []*schema.Column{PostmortemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "actionitem_status",
				Unique:  false,
				Columns: []*schema.Column{ActionItemsColumns[4]},
			},
			{
				Name:    "actionitem_due_date",
				Unique:  false,
				Columns: []*schema.Column{ActionItemsColumns[3]},
			},
		},
	}
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "actor_user_id", Type: field.TypeInt, Default: 0},
		{Name: "actor_name", Type: field.TypeString, Default: "system"},
		{Name: "action", Type: field.TypeString},
		{Name: "resource_type", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeInt, Default: 0},
		{Name: "resource_name", Type: field.TypeString, Nullable: true},
		{Name: "result", Type: field.TypeEnum, Enums: []string{"success", "failed", "denied"}, Default: "success"},
		{Name: "detail", Type: field.TypeJSON, Nullable: true},
		{Name: "ip", Type: field.TypeString, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_actor_user_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[1]},
			},
			{
				Name:    "auditlog_action",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[3]},
			},
			{
				Name:    "auditlog_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[4], AuditLogsColumns[5]},
			},
			{
				Name:    "auditlog_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[11]},
			},
		},
	}
	// EscalationPoliciesColumns holds the columns for the "escalation_policies" table.
	EscalationPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "repeat_times", Type: field.TypeInt, Default: 0},
		{Name: "levels", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "team_escalation_policies", Type: field.TypeInt, Nullable: true},
	}
	// EscalationPoliciesTable holds the schema information for the "escalation_policies" table.
	EscalationPoliciesTable = &schema.Table{
		Name:       "escalation_policies",
		Columns:    EscalationPoliciesColumns,
		PrimaryKey: []*schema.Column{EscalationPoliciesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "escalation_policies_teams_escalation_policies",
				Columns:    []*schema.Column{EscalationPoliciesColumns[6]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source_event_id", Type: field.TypeString},
		{Name: "source", Type: field.TypeString},
		{Name: "severity", Type: field.TypeEnum, Enums: []string{"critical", "warning", "info"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"firing", "resolved"}},
		{Name: "summary", Type: field.TypeString},
		{Name: "detail", Type: field.TypeJSON, Nullable: true},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "dedup_key", Type: field.TypeString},
		{Name: "received_at", Type: field.TypeTime},
		{Name: "is_noise", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "event_incident", Type: field.TypeInt, Nullable: true},
		{Name: "integration_events", Type: field.TypeInt, Nullable: true},
		{Name: "service_events", Type: field.TypeInt, Nullable: true},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_incidents_incident",
				Columns:    []*schema.Column{EventsColumns[12]},
				RefColumns: []*schema.Column{IncidentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "events_integrations_events",
				Columns:    []*schema.Column{EventsColumns[13]},
				RefColumns: []*schema.Column{IntegrationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "events_services_events",
				Columns:    []*schema.Column{EventsColumns[14]},
				RefColumns: []*schema.Column{ServicesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "event_dedup_key",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[8]},
			},
			{
				Name:    "event_source_source_event_id_status",
				Unique:  true,
				Columns: []*schema.Column{EventsColumns[2], EventsColumns[1], EventsColumns[4]},
			},
			{
				Name:    "event_severity_received_at",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[3], EventsColumns[9]},
			},
			{
				Name:    "event_is_noise",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[10]},
			},
		},
	}
	// ImAccountBindingsColumns holds the columns for the "im_account_bindings" table.
	ImAccountBindingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "platform", Type: field.TypeEnum, Enums: []string{"feishu", "dingtalk", "wecom"}},
		{Name: "account_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_im_bindings", Type: field.TypeInt},
	}
	// ImAccountBindingsTable holds the schema information for the "im_account_bindings" table.
	ImAccountBindingsTable = &schema.Table{
		Name:       "im_account_bindings",
		Columns:    ImAccountBindingsColumns,
		PrimaryKey: []*schema.Column{ImAccountBindingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "im_account_bindings_users_im_bindings",
				Columns:    []*schema.Column{ImAccountBindingsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "imaccountbinding_platform_account_id",
				Unique:  true,
				Columns: []*schema.Column{ImAccountBindingsColumns[1], ImAccountBindingsColumns[2]},
			},
		},
	}
	// IncidentsColumns holds the columns for the "incidents" table.
	IncidentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "number", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "severity", Type: field.TypeEnum, Enums: []string{"critical", "warning", "info"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"triggered", "escalated", "acked", "resolved", "closed"}, Default: "triggered"},
		{Name: "priority", Type: field.TypeEnum, Enums: []string{"p1", "p2", "p3", "p4"}, Default: "p3"},
		{Name: "summary", Type: field.TypeString, Nullable: true},
		{Name: "escalated_count", Type: field.TypeInt, Default: 0},
		{Name: "current_level", Type: field.TypeInt, Default: 0},
		{Name: "merged_into", Type: field.TypeString, Nullable: true},
		{Name: "trigger_type", Type: field.TypeEnum, Enums: []string{"auto", "manual", "merged"}, Default: "auto"},
		{Name: "trigger_source_event_id", Type: field.TypeString, Nullable: true},
		{Name: "war_room", Type: field.TypeJSON, Nullable: true},
		{Name: "resolved_at", Type: field.TypeTime, Nullable: true},
		{Name: "postmortem_skipped", Type: field.TypeBool, Default: false},
		{Name: "acked_at", Type: field.TypeTime, Nullable: true},
		{Name: "closed_at", Type: field.TypeTime, Nullable: true},
		{Name: "embedding", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "vector(1536)", "sqlite3": "blob"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "escalation_policy_incidents", Type: field.TypeInt, Nullable: true},
		{Name: "incident_assignee", Type: field.TypeInt, Nullable: true},
		{Name: "service_incidents", Type: field.TypeInt, Nullable: true},
		{Name: "team_incidents", Type: field.TypeInt, Nullable: true},
	}
	// IncidentsTable holds the schema information for the "incidents" table.
	IncidentsTable = &schema.Table{
		Name:       "incidents",
		Columns:    IncidentsColumns,
		PrimaryKey: []*schema.Column{IncidentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "incidents_escalation_policies_incidents",
				Columns:    []*schema.Column{IncidentsColumns[20]},
				RefColumns: []*schema.Column{EscalationPoliciesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "incidents_users_assignee",
				Columns:    []*schema.Column{IncidentsColumns[21]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "incidents_services_incidents",
				Columns:    []*schema.Column{IncidentsColumns[22]},
				RefColumns: []*schema.Column{ServicesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "incidents_teams_incidents",
				Columns:    []*schema.Column{IncidentsColumns[23]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "incident_status_severity",
				Unique:  false,
				Columns: []*schema.Column{IncidentsColumns[4], IncidentsColumns[3]},
			},
			{
				Name:    "incident_team_incidents",
				Unique:  false,
				Columns: []*schema.Column{IncidentsColumns[23]},
			},
			{
				Name:    "incident_service_incidents",
				Unique:  false,
				Columns: []*schema.Column{IncidentsColumns[22]},
			},
			{
				Name:    "incident_resolved_at",
				Unique:  false,
				Columns: []*schema.Column{IncidentsColumns[13]},
			},
		},
	}
	// IncidentActionsColumns holds the columns for the "incident_actions" table.
	IncidentActionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"ack", "escalate", "resolve", "reopen", "close", "snooze", "reassign", "add_responder", "runbook", "custom"}},
		{Name: "actor", Type: field.TypeJSON},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "via", Type: field.TypeEnum, Enums: []string{"web", "im", "api", "automation"}},
		{Name: "result", Type: field.TypeEnum, Enums: []string{"success", "failed", "pending"}, Default: "success"},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "incident_actions", Type: field.TypeInt, Nullable: true},
	}
	// IncidentActionsTable holds the schema information for the "incident_actions" table.
	IncidentActionsTable = &schema.Table{
		Name:       "incident_actions",
		Columns:    IncidentActionsColumns,
		PrimaryKey: []*schema.Column{IncidentActionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "incident_actions_incidents_actions",
				Columns:    []*schema.Column{IncidentActionsColumns[7]},
				RefColumns: []*schema.Column{IncidentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "incidentaction_incident_actions",
				Unique:  false,
				Columns: []*schema.Column{IncidentActionsColumns[7]},
			},
			{
				Name:    "incidentaction_timestamp",
				Unique:  false,
				Columns: []*schema.Column{IncidentActionsColumns[6]},
			},
			{
				Name:    "incidentaction_via_timestamp",
				Unique:  false,
				Columns: []*schema.Column{IncidentActionsColumns[4], IncidentActionsColumns[6]},
			},
		},
	}
	// IntegrationsColumns holds the columns for the "integrations" table.
	IntegrationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"webhook", "email", "prometheus", "zabbix", "grafana", "cloud", "api"}},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
		{Name: "token", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "service_integrations", Type: field.TypeInt, Nullable: true},
		{Name: "team_integrations", Type: field.TypeInt, Nullable: true},
	}
	// IntegrationsTable holds the schema information for the "integrations" table.
	IntegrationsTable = &schema.Table{
		Name:       "integrations",
		Columns:    IntegrationsColumns,
		PrimaryKey: []*schema.Column{IntegrationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "integrations_services_integrations",
				Columns:    []*schema.Column{IntegrationsColumns[8]},
				RefColumns: []*schema.Column{ServicesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "integrations_teams_integrations",
				Columns:    []*schema.Column{IntegrationsColumns[9]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channel", Type: field.TypeString},
		{Name: "target", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "sent", "failed", "suppressed"}, Default: "pending"},
		{Name: "reason", Type: field.TypeString, Nullable: true},
		{Name: "level", Type: field.TypeInt, Default: 0},
		{Name: "severity", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "incident_notifications", Type: field.TypeInt, Nullable: true},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notifications_incidents_notifications",
				Columns:    []*schema.Column{NotificationsColumns[9]},
				RefColumns: []*schema.Column{IncidentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notification_incident_notifications",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[9]},
			},
			{
				Name:    "notification_status",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[4]},
			},
			{
				Name:    "notification_channel",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[1]},
			},
			{
				Name:    "notification_created_at",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[8]},
			},
		},
	}
	// NotificationRulesColumns holds the columns for the "notification_rules" table.
	NotificationRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "condition", Type: field.TypeJSON},
		{Name: "channels", Type: field.TypeJSON},
		{Name: "template_id", Type: field.TypeString, Nullable: true},
		{Name: "quiet_hours", Type: field.TypeJSON, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "team_notification_rules", Type: field.TypeInt, Nullable: true},
	}
	// NotificationRulesTable holds the schema information for the "notification_rules" table.
	NotificationRulesTable = &schema.Table{
		Name:       "notification_rules",
		Columns:    NotificationRulesColumns,
		PrimaryKey: []*schema.Column{NotificationRulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notification_rules_teams_notification_rules",
				Columns:    []*schema.Column{NotificationRulesColumns[9]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// NotificationTemplatesColumns holds the columns for the "notification_templates" table.
	NotificationTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "channel", Type: field.TypeEnum, Enums: []string{"im", "email", "webhook", "phone", "sms"}},
		{Name: "format", Type: field.TypeEnum, Enums: []string{"text", "interactive_card"}},
		{Name: "title_template", Type: field.TypeString},
		{Name: "body_template", Type: field.TypeString, Size: 2147483647},
		{Name: "actions", Type: field.TypeJSON, Nullable: true},
		{Name: "builtin", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "team_notification_templates", Type: field.TypeInt, Nullable: true},
	}
	// NotificationTemplatesTable holds the schema information for the "notification_templates" table.
	NotificationTemplatesTable = &schema.Table{
		Name:       "notification_templates",
		Columns:    NotificationTemplatesColumns,
		PrimaryKey: []*schema.Column{NotificationTemplatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notification_templates_teams_notification_templates",
				Columns:    []*schema.Column{NotificationTemplatesColumns[10]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OverridesColumns holds the columns for the "overrides" table.
	OverridesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "end_time", Type: field.TypeTime},
		{Name: "reason", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "override_user", Type: field.TypeInt},
		{Name: "override_created_by", Type: field.TypeInt, Nullable: true},
		{Name: "schedule_overrides", Type: field.TypeInt},
	}
	// OverridesTable holds the schema information for the "overrides" table.
	OverridesTable = &schema.Table{
		Name:       "overrides",
		Columns:    OverridesColumns,
		PrimaryKey: []*schema.Column{OverridesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "overrides_users_user",
				Columns:    []*schema.Column{OverridesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "overrides_users_created_by",
				Columns:    []*schema.Column{OverridesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "overrides_schedules_overrides",
				Columns:    []*schema.Column{OverridesColumns[7]},
				RefColumns: []*schema.Column{SchedulesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PostmortemsColumns holds the columns for the "postmortems" table.
	PostmortemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "in_review", "published", "archived"}, Default: "draft"},
		{Name: "generated_by", Type: field.TypeEnum, Enums: []string{"ai", "human", "mixed"}, Default: "mixed"},
		{Name: "sections", Type: field.TypeJSON},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "embedding", Type: field.TypeOther, Nullable: true, SchemaType: map[string]string{"postgres": "vector(1536)", "sqlite3": "blob"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "incident_postmortem", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// PostmortemsTable holds the schema information for the "postmortems" table.
	PostmortemsTable = &schema.Table{
		Name:       "postmortems",
		Columns:    PostmortemsColumns,
		PrimaryKey: []*schema.Column{PostmortemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "postmortems_incidents_postmortem",
				Columns:    []*schema.Column{PostmortemsColumns[8]},
				RefColumns: []*schema.Column{IncidentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RawEventsColumns holds the columns for the "raw_events" table.
	RawEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "payload", Type: field.TypeBytes},
		{Name: "headers", Type: field.TypeJSON, Nullable: true},
		{Name: "received_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"received", "normalized", "parse_failed", "requeued"}, Default: "received"},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "integration_raw_events", Type: field.TypeInt, Nullable: true},
	}
	// RawEventsTable holds the schema information for the "raw_events" table.
	RawEventsTable = &schema.Table{
		Name:       "raw_events",
		Columns:    RawEventsColumns,
		PrimaryKey: []*schema.Column{RawEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "raw_events_integrations_raw_events",
				Columns:    []*schema.Column{RawEventsColumns[7]},
				RefColumns: []*schema.Column{IntegrationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rawevent_status_received_at",
				Unique:  false,
				Columns: []*schema.Column{RawEventsColumns[4], RawEventsColumns[3]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "builtin", Type: field.TypeBool, Default: false},
		{Name: "scope_level", Type: field.TypeEnum, Enums: []string{"org", "team"}},
		{Name: "permissions", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// RoleBindingsColumns holds the columns for the "role_bindings" table.
	RoleBindingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "scope_level", Type: field.TypeEnum, Enums: []string{"org", "team"}},
		{Name: "team_id", Type: field.TypeString, Nullable: true},
		{Name: "granted_by", Type: field.TypeString, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "granted_at", Type: field.TypeTime},
		{Name: "role_role_bindings", Type: field.TypeInt},
		{Name: "user_role_bindings", Type: field.TypeInt},
	}
	// RoleBindingsTable holds the schema information for the "role_bindings" table.
	RoleBindingsTable = &schema.Table{
		Name:       "role_bindings",
		Columns:    RoleBindingsColumns,
		PrimaryKey: []*schema.Column{RoleBindingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_bindings_roles_role_bindings",
				Columns:    []*schema.Column{RoleBindingsColumns[6]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "role_bindings_users_role_bindings",
				Columns:    []*schema.Column{RoleBindingsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RotationsColumns holds the columns for the "rotations" table.
	RotationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "shift_length", Type: field.TypeString, Default: "24h"},
		{Name: "handoff_time", Type: field.TypeString, Default: "09:00"},
		{Name: "rotation_type", Type: field.TypeEnum, Enums: []string{"daily", "weekly", "custom"}},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "schedule_rotations", Type: field.TypeInt, Nullable: true},
	}
	// RotationsTable holds the schema information for the "rotations" table.
	RotationsTable = &schema.Table{
		Name:       "rotations",
		Columns:    RotationsColumns,
		PrimaryKey: []*schema.Column{RotationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rotations_schedules_rotations",
				Columns:    []*schema.Column{RotationsColumns[9]},
				RefColumns: []*schema.Column{SchedulesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RunbooksColumns holds the columns for the "runbooks" table.
	RunbooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"document", "executable"}},
		{Name: "trigger", Type: field.TypeJSON, Nullable: true},
		{Name: "content_markdown", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "steps", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "team_runbooks", Type: field.TypeInt, Nullable: true},
	}
	// RunbooksTable holds the schema information for the "runbooks" table.
	RunbooksTable = &schema.Table{
		Name:       "runbooks",
		Columns:    RunbooksColumns,
		PrimaryKey: []*schema.Column{RunbooksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "runbooks_teams_runbooks",
				Columns:    []*schema.Column{RunbooksColumns[8]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SchedulesColumns holds the columns for the "schedules" table.
	SchedulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"calendar", "rotation", "follow_the_sun"}},
		{Name: "timezone", Type: field.TypeString, Default: "Asia/Shanghai"},
		{Name: "layers", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "team_schedules", Type: field.TypeInt, Nullable: true},
	}
	// SchedulesTable holds the schema information for the "schedules" table.
	SchedulesTable = &schema.Table{
		Name:       "schedules",
		Columns:    SchedulesColumns,
		PrimaryKey: []*schema.Column{SchedulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "schedules_teams_schedules",
				Columns:    []*schema.Column{SchedulesColumns[7]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ServicesColumns holds the columns for the "services" table.
	ServicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "labels", Type: field.TypeJSON, Nullable: true},
		{Name: "auto_create_incident", Type: field.TypeBool, Default: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "service_escalation_policy", Type: field.TypeInt, Nullable: true},
		{Name: "team_services", Type: field.TypeInt, Nullable: true},
	}
	// ServicesTable holds the schema information for the "services" table.
	ServicesTable = &schema.Table{
		Name:       "services",
		Columns:    ServicesColumns,
		PrimaryKey: []*schema.Column{ServicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "services_escalation_policies_escalation_policy",
				Columns:    []*schema.Column{ServicesColumns[9]},
				RefColumns: []*schema.Column{EscalationPoliciesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "services_teams_services",
				Columns:    []*schema.Column{ServicesColumns[10]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "service_status",
				Unique:  false,
				Columns: []*schema.Column{ServicesColumns[6]},
			},
		},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "channels", Type: field.TypeJSON, Nullable: true},
		{Name: "min_severity", Type: field.TypeEnum, Enums: []string{"critical", "warning", "info"}, Default: "warning"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "service_subscriptions", Type: field.TypeInt, Nullable: true},
		{Name: "team_subscriptions", Type: field.TypeInt, Nullable: true},
		{Name: "user_subscriptions", Type: field.TypeInt},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subscriptions_services_subscriptions",
				Columns:    []*schema.Column{SubscriptionsColumns[5]},
				RefColumns: []*schema.Column{ServicesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "subscriptions_teams_subscriptions",
				Columns:    []*schema.Column{SubscriptionsColumns[6]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "subscriptions_users_subscriptions",
				Columns:    []*schema.Column{SubscriptionsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "subscription_user_subscriptions",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionsColumns[7]},
			},
			{
				Name:    "subscription_team_subscriptions",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionsColumns[6]},
			},
			{
				Name:    "subscription_service_subscriptions",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionsColumns[5]},
			},
		},
	}
	// SuppressionRulesColumns holds the columns for the "suppression_rules" table.
	SuppressionRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "match_labels", Type: field.TypeJSON},
		{Name: "time_window", Type: field.TypeJSON, Nullable: true},
		{Name: "severity_filter", Type: field.TypeJSON, Nullable: true},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"suppress", "reduce_severity"}, Default: "suppress"},
		{Name: "reduce_to", Type: field.TypeString, Nullable: true},
		{Name: "preserve_critical", Type: field.TypeBool, Default: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "team_suppression_rules", Type: field.TypeInt, Nullable: true},
	}
	// SuppressionRulesTable holds the schema information for the "suppression_rules" table.
	SuppressionRulesTable = &schema.Table{
		Name:       "suppression_rules",
		Columns:    SuppressionRulesColumns,
		PrimaryKey: []*schema.Column{SuppressionRulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "suppression_rules_teams_suppression_rules",
				Columns:    []*schema.Column{SuppressionRulesColumns[12]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "parent_team_id", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "team_parent_team_id",
				Unique:  false,
				Columns: []*schema.Column{TeamsColumns[4]},
			},
		},
	}
	// TicketIntegrationsColumns holds the columns for the "ticket_integrations" table.
	TicketIntegrationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"webhook", "jira", "zentao"}, Default: "webhook"},
		{Name: "endpoint", Type: field.TypeString},
		{Name: "credential", Type: field.TypeString, Nullable: true},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "team_ticket_integrations", Type: field.TypeInt, Nullable: true},
	}
	// TicketIntegrationsTable holds the schema information for the "ticket_integrations" table.
	TicketIntegrationsTable = &schema.Table{
		Name:       "ticket_integrations",
		Columns:    TicketIntegrationsColumns,
		PrimaryKey: []*schema.Column{TicketIntegrationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ticket_integrations_teams_ticket_integrations",
				Columns:    []*schema.Column{TicketIntegrationsColumns[9]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "ticketintegration_enabled",
				Unique:  false,
				Columns: []*schema.Column{TicketIntegrationsColumns[6]},
			},
		},
	}
	// TimelineItemsColumns holds the columns for the "timeline_items" table.
	TimelineItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"incident_created", "event_attached", "status_changed", "escalated", "ack", "resolved", "reopened", "responder_added", "note_added", "runbook_executed", "ai_insight", "im_message"}},
		{Name: "actor", Type: field.TypeJSON},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "detail", Type: field.TypeJSON, Nullable: true},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"web", "im", "api", "system", "ai"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "incident_timeline", Type: field.TypeInt, Nullable: true},
	}
	// TimelineItemsTable holds the schema information for the "timeline_items" table.
	TimelineItemsTable = &schema.Table{
		Name:       "timeline_items",
		Columns:    TimelineItemsColumns,
		PrimaryKey: []*schema.Column{TimelineItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "timeline_items_incidents_timeline",
				Columns:    []*schema.Column{TimelineItemsColumns[8]},
				RefColumns: []*schema.Column{IncidentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "timelineitem_incident_timeline",
				Unique:  false,
				Columns: []*schema.Column{TimelineItemsColumns[8]},
			},
			{
				Name:    "timelineitem_timestamp",
				Unique:  false,
				Columns: []*schema.Column{TimelineItemsColumns[1]},
			},
			{
				Name:    "timelineitem_type",
				Unique:  false,
				Columns: []*schema.Column{TimelineItemsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "im_accounts", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "timezone", Type: field.TypeString, Default: "Asia/Shanghai"},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "must_change_password", Type: field.TypeBool, Default: false},
		{Name: "token_version", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[6]},
			},
		},
	}
	// WebhookDeliveriesColumns holds the columns for the "webhook_deliveries" table.
	WebhookDeliveriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
		{Name: "event", Type: field.TypeString},
		{Name: "incident_id", Type: field.TypeInt, Nullable: true},
		{Name: "payload", Type: field.TypeBytes},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"success", "failed"}, Default: "failed"},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "last_status_code", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// WebhookDeliveriesTable holds the schema information for the "webhook_deliveries" table.
	WebhookDeliveriesTable = &schema.Table{
		Name:       "webhook_deliveries",
		Columns:    WebhookDeliveriesColumns,
		PrimaryKey: []*schema.Column{WebhookDeliveriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "webhookdelivery_status",
				Unique:  false,
				Columns: []*schema.Column{WebhookDeliveriesColumns[5]},
			},
			{
				Name:    "webhookdelivery_incident_id",
				Unique:  false,
				Columns: []*schema.Column{WebhookDeliveriesColumns[3]},
			},
		},
	}
	// EscalationPolicySchedulesColumns holds the columns for the "escalation_policy_schedules" table.
	EscalationPolicySchedulesColumns = []*schema.Column{
		{Name: "escalation_policy_id", Type: field.TypeInt},
		{Name: "schedule_id", Type: field.TypeInt},
	}
	// EscalationPolicySchedulesTable holds the schema information for the "escalation_policy_schedules" table.
	EscalationPolicySchedulesTable = &schema.Table{
		Name:       "escalation_policy_schedules",
		Columns:    EscalationPolicySchedulesColumns,
		PrimaryKey: []*schema.Column{EscalationPolicySchedulesColumns[0], EscalationPolicySchedulesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "escalation_policy_schedules_escalation_policy_id",
				Columns:    []*schema.Column{EscalationPolicySchedulesColumns[0]},
				RefColumns: []*schema.Column{EscalationPoliciesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "escalation_policy_schedules_schedule_id",
				Columns:    []*schema.Column{EscalationPolicySchedulesColumns[1]},
				RefColumns: []*schema.Column{SchedulesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// IncidentRespondersColumns holds the columns for the "incident_responders" table.
	IncidentRespondersColumns = []*schema.Column{
		{Name: "incident_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// IncidentRespondersTable holds the schema information for the "incident_responders" table.
	IncidentRespondersTable = &schema.Table{
		Name:       "incident_responders",
		Columns:    IncidentRespondersColumns,
		PrimaryKey: []*schema.Column{IncidentRespondersColumns[0], IncidentRespondersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "incident_responders_incident_id",
				Columns:    []*schema.Column{IncidentRespondersColumns[0]},
				RefColumns: []*schema.Column{IncidentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "incident_responders_user_id",
				Columns:    []*schema.Column{IncidentRespondersColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// RotationParticipantsColumns holds the columns for the "rotation_participants" table.
	RotationParticipantsColumns = []*schema.Column{
		{Name: "rotation_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// RotationParticipantsTable holds the schema information for the "rotation_participants" table.
	RotationParticipantsTable = &schema.Table{
		Name:       "rotation_participants",
		Columns:    RotationParticipantsColumns,
		PrimaryKey: []*schema.Column{RotationParticipantsColumns[0], RotationParticipantsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rotation_participants_rotation_id",
				Columns:    []*schema.Column{RotationParticipantsColumns[0]},
				RefColumns: []*schema.Column{RotationsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "rotation_participants_user_id",
				Columns:    []*schema.Column{RotationParticipantsColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ServiceSchedulesColumns holds the columns for the "service_schedules" table.
	ServiceSchedulesColumns = []*schema.Column{
		{Name: "service_id", Type: field.TypeInt},
		{Name: "schedule_id", Type: field.TypeInt},
	}
	// ServiceSchedulesTable holds the schema information for the "service_schedules" table.
	ServiceSchedulesTable = &schema.Table{
		Name:       "service_schedules",
		Columns:    ServiceSchedulesColumns,
		PrimaryKey: []*schema.Column{ServiceSchedulesColumns[0], ServiceSchedulesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "service_schedules_service_id",
				Columns:    []*schema.Column{ServiceSchedulesColumns[0]},
				RefColumns: []*schema.Column{ServicesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "service_schedules_schedule_id",
				Columns:    []*schema.Column{ServiceSchedulesColumns[1]},
				RefColumns: []*schema.Column{SchedulesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ServiceRunbooksColumns holds the columns for the "service_runbooks" table.
	ServiceRunbooksColumns = []*schema.Column{
		{Name: "service_id", Type: field.TypeInt},
		{Name: "runbook_id", Type: field.TypeInt},
	}
	// ServiceRunbooksTable holds the schema information for the "service_runbooks" table.
	ServiceRunbooksTable = &schema.Table{
		Name:       "service_runbooks",
		Columns:    ServiceRunbooksColumns,
		PrimaryKey: []*schema.Column{ServiceRunbooksColumns[0], ServiceRunbooksColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "service_runbooks_service_id",
				Columns:    []*schema.Column{ServiceRunbooksColumns[0]},
				RefColumns: []*schema.Column{ServicesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "service_runbooks_runbook_id",
				Columns:    []*schema.Column{ServiceRunbooksColumns[1]},
				RefColumns: []*schema.Column{RunbooksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TeamUsersColumns holds the columns for the "team_users" table.
	TeamUsersColumns = []*schema.Column{
		{Name: "team_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// TeamUsersTable holds the schema information for the "team_users" table.
	TeamUsersTable = &schema.Table{
		Name:       "team_users",
		Columns:    TeamUsersColumns,
		PrimaryKey: []*schema.Column{TeamUsersColumns[0], TeamUsersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "team_users_team_id",
				Columns:    []*schema.Column{TeamUsersColumns[0]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "team_users_user_id",
				Columns:    []*schema.Column{TeamUsersColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TeamRoleBindingsColumns holds the columns for the "team_role_bindings" table.
	TeamRoleBindingsColumns = []*schema.Column{
		{Name: "team_id", Type: field.TypeInt},
		{Name: "role_binding_id", Type: field.TypeInt},
	}
	// TeamRoleBindingsTable holds the schema information for the "team_role_bindings" table.
	TeamRoleBindingsTable = &schema.Table{
		Name:       "team_role_bindings",
		Columns:    TeamRoleBindingsColumns,
		PrimaryKey: []*schema.Column{TeamRoleBindingsColumns[0], TeamRoleBindingsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "team_role_bindings_team_id",
				Columns:    []*schema.Column{TeamRoleBindingsColumns[0]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "team_role_bindings_role_binding_id",
				Columns:    []*schema.Column{TeamRoleBindingsColumns[1]},
				RefColumns: []*schema.Column{RoleBindingsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AiInsightsTable,
		APIKeysTable,
		ActionItemsTable,
		AuditLogsTable,
		EscalationPoliciesTable,
		EventsTable,
		ImAccountBindingsTable,
		IncidentsTable,
		IncidentActionsTable,
		IntegrationsTable,
		NotificationsTable,
		NotificationRulesTable,
		NotificationTemplatesTable,
		OverridesTable,
		PostmortemsTable,
		RawEventsTable,
		RolesTable,
		RoleBindingsTable,
		RotationsTable,
		RunbooksTable,
		SchedulesTable,
		ServicesTable,
		SubscriptionsTable,
		SuppressionRulesTable,
		TeamsTable,
		TicketIntegrationsTable,
		TimelineItemsTable,
		UsersTable,
		WebhookDeliveriesTable,
		EscalationPolicySchedulesTable,
		IncidentRespondersTable,
		RotationParticipantsTable,
		ServiceSchedulesTable,
		ServiceRunbooksTable,
		TeamUsersTable,
		TeamRoleBindingsTable,
	}
)

func init() {
	AiInsightsTable.ForeignKeys[0].RefTable = IncidentsTable
	APIKeysTable.ForeignKeys[0].RefTable = UsersTable
	ActionItemsTable.ForeignKeys[0].RefTable = PostmortemsTable
	EscalationPoliciesTable.ForeignKeys[0].RefTable = TeamsTable
	EventsTable.ForeignKeys[0].RefTable = IncidentsTable
	EventsTable.ForeignKeys[1].RefTable = IntegrationsTable
	EventsTable.ForeignKeys[2].RefTable = ServicesTable
	ImAccountBindingsTable.ForeignKeys[0].RefTable = UsersTable
	IncidentsTable.ForeignKeys[0].RefTable = EscalationPoliciesTable
	IncidentsTable.ForeignKeys[1].RefTable = UsersTable
	IncidentsTable.ForeignKeys[2].RefTable = ServicesTable
	IncidentsTable.ForeignKeys[3].RefTable = TeamsTable
	IncidentActionsTable.ForeignKeys[0].RefTable = IncidentsTable
	IntegrationsTable.ForeignKeys[0].RefTable = ServicesTable
	IntegrationsTable.ForeignKeys[1].RefTable = TeamsTable
	NotificationsTable.ForeignKeys[0].RefTable = IncidentsTable
	NotificationRulesTable.ForeignKeys[0].RefTable = TeamsTable
	NotificationTemplatesTable.ForeignKeys[0].RefTable = TeamsTable
	OverridesTable.ForeignKeys[0].RefTable = UsersTable
	OverridesTable.ForeignKeys[1].RefTable = UsersTable
	OverridesTable.ForeignKeys[2].RefTable = SchedulesTable
	PostmortemsTable.ForeignKeys[0].RefTable = IncidentsTable
	RawEventsTable.ForeignKeys[0].RefTable = IntegrationsTable
	RoleBindingsTable.ForeignKeys[0].RefTable = RolesTable
	RoleBindingsTable.ForeignKeys[1].RefTable = UsersTable
	RotationsTable.ForeignKeys[0].RefTable = SchedulesTable
	RunbooksTable.ForeignKeys[0].RefTable = TeamsTable
	SchedulesTable.ForeignKeys[0].RefTable = TeamsTable
	ServicesTable.ForeignKeys[0].RefTable = EscalationPoliciesTable
	ServicesTable.ForeignKeys[1].RefTable = TeamsTable
	SubscriptionsTable.ForeignKeys[0].RefTable = ServicesTable
	SubscriptionsTable.ForeignKeys[1].RefTable = TeamsTable
	SubscriptionsTable.ForeignKeys[2].RefTable = UsersTable
	SuppressionRulesTable.ForeignKeys[0].RefTable = TeamsTable
	TicketIntegrationsTable.ForeignKeys[0].RefTable = TeamsTable
	TimelineItemsTable.ForeignKeys[0].RefTable = IncidentsTable
	EscalationPolicySchedulesTable.ForeignKeys[0].RefTable = EscalationPoliciesTable
	EscalationPolicySchedulesTable.ForeignKeys[1].RefTable = SchedulesTable
	IncidentRespondersTable.ForeignKeys[0].RefTable = IncidentsTable
	IncidentRespondersTable.ForeignKeys[1].RefTable = UsersTable
	RotationParticipantsTable.ForeignKeys[0].RefTable = RotationsTable
	RotationParticipantsTable.ForeignKeys[1].RefTable = UsersTable
	ServiceSchedulesTable.ForeignKeys[0].RefTable = ServicesTable
	ServiceSchedulesTable.ForeignKeys[1].RefTable = SchedulesTable
	ServiceRunbooksTable.ForeignKeys[0].RefTable = ServicesTable
	ServiceRunbooksTable.ForeignKeys[1].RefTable = RunbooksTable
	TeamUsersTable.ForeignKeys[0].RefTable = TeamsTable
	TeamUsersTable.ForeignKeys[1].RefTable = UsersTable
	TeamRoleBindingsTable.ForeignKeys[0].RefTable = TeamsTable
	TeamRoleBindingsTable.ForeignKeys[1].RefTable = RoleBindingsTable
}
