// Code generated by ent, DO NOT EDIT.

package incident

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the incident type in the database.
	Label = "incident"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldEscalatedCount holds the string denoting the escalated_count field in the database.
	FieldEscalatedCount = "escalated_count"
	// FieldCurrentLevel holds the string denoting the current_level field in the database.
	FieldCurrentLevel = "current_level"
	// FieldMergedInto holds the string denoting the merged_into field in the database.
	FieldMergedInto = "merged_into"
	// FieldTriggerType holds the string denoting the trigger_type field in the database.
	FieldTriggerType = "trigger_type"
	// FieldTriggerSourceEventID holds the string denoting the trigger_source_event_id field in the database.
	FieldTriggerSourceEventID = "trigger_source_event_id"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldPostmortemSkipped holds the string denoting the postmortem_skipped field in the database.
	FieldPostmortemSkipped = "postmortem_skipped"
	// FieldAckedAt holds the string denoting the acked_at field in the database.
	FieldAckedAt = "acked_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// FieldEmbedding holds the string denoting the embedding field in the database.
	FieldEmbedding = "embedding"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTeam holds the string denoting the team edge name in mutations.
	EdgeTeam = "team"
	// EdgeService holds the string denoting the service edge name in mutations.
	EdgeService = "service"
	// EdgeEscalationPolicy holds the string denoting the escalation_policy edge name in mutations.
	EdgeEscalationPolicy = "escalation_policy"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EdgeAssignee holds the string denoting the assignee edge name in mutations.
	EdgeAssignee = "assignee"
	// EdgeResponders holds the string denoting the responders edge name in mutations.
	EdgeResponders = "responders"
	// EdgeTimeline holds the string denoting the timeline edge name in mutations.
	EdgeTimeline = "timeline"
	// EdgeActions holds the string denoting the actions edge name in mutations.
	EdgeActions = "actions"
	// EdgePostmortem holds the string denoting the postmortem edge name in mutations.
	EdgePostmortem = "postmortem"
	// EdgeAiInsights holds the string denoting the ai_insights edge name in mutations.
	EdgeAiInsights = "ai_insights"
	// EdgeNotifications holds the string denoting the notifications edge name in mutations.
	EdgeNotifications = "notifications"
	// Table holds the table name of the incident in the database.
	Table = "incidents"
	// TeamTable is the table that holds the team relation/edge.
	TeamTable = "incidents"
	// TeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamInverseTable = "teams"
	// TeamColumn is the table column denoting the team relation/edge.
	TeamColumn = "team_incidents"
	// ServiceTable is the table that holds the service relation/edge.
	ServiceTable = "incidents"
	// ServiceInverseTable is the table name for the Service entity.
	// It exists in this package in order to avoid circular dependency with the "service" package.
	ServiceInverseTable = "services"
	// ServiceColumn is the table column denoting the service relation/edge.
	ServiceColumn = "service_incidents"
	// EscalationPolicyTable is the table that holds the escalation_policy relation/edge.
	EscalationPolicyTable = "incidents"
	// EscalationPolicyInverseTable is the table name for the EscalationPolicy entity.
	// It exists in this package in order to avoid circular dependency with the "escalationpolicy" package.
	EscalationPolicyInverseTable = "escalation_policies"
	// EscalationPolicyColumn is the table column denoting the escalation_policy relation/edge.
	EscalationPolicyColumn = "escalation_policy_incidents"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "events"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "event_incident"
	// AssigneeTable is the table that holds the assignee relation/edge.
	AssigneeTable = "incidents"
	// AssigneeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AssigneeInverseTable = "users"
	// AssigneeColumn is the table column denoting the assignee relation/edge.
	AssigneeColumn = "incident_assignee"
	// RespondersTable is the table that holds the responders relation/edge. The primary key declared below.
	RespondersTable = "incident_responders"
	// RespondersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	RespondersInverseTable = "users"
	// TimelineTable is the table that holds the timeline relation/edge.
	TimelineTable = "timeline_items"
	// TimelineInverseTable is the table name for the TimelineItem entity.
	// It exists in this package in order to avoid circular dependency with the "timelineitem" package.
	TimelineInverseTable = "timeline_items"
	// TimelineColumn is the table column denoting the timeline relation/edge.
	TimelineColumn = "incident_timeline"
	// ActionsTable is the table that holds the actions relation/edge.
	ActionsTable = "incident_actions"
	// ActionsInverseTable is the table name for the IncidentAction entity.
	// It exists in this package in order to avoid circular dependency with the "incidentaction" package.
	ActionsInverseTable = "incident_actions"
	// ActionsColumn is the table column denoting the actions relation/edge.
	ActionsColumn = "incident_actions"
	// PostmortemTable is the table that holds the postmortem relation/edge.
	PostmortemTable = "postmortems"
	// PostmortemInverseTable is the table name for the Postmortem entity.
	// It exists in this package in order to avoid circular dependency with the "postmortem" package.
	PostmortemInverseTable = "postmortems"
	// PostmortemColumn is the table column denoting the postmortem relation/edge.
	PostmortemColumn = "incident_postmortem"
	// AiInsightsTable is the table that holds the ai_insights relation/edge.
	AiInsightsTable = "ai_insights"
	// AiInsightsInverseTable is the table name for the AIInsight entity.
	// It exists in this package in order to avoid circular dependency with the "aiinsight" package.
	AiInsightsInverseTable = "ai_insights"
	// AiInsightsColumn is the table column denoting the ai_insights relation/edge.
	AiInsightsColumn = "incident_ai_insights"
	// NotificationsTable is the table that holds the notifications relation/edge.
	NotificationsTable = "notifications"
	// NotificationsInverseTable is the table name for the Notification entity.
	// It exists in this package in order to avoid circular dependency with the "notification" package.
	NotificationsInverseTable = "notifications"
	// NotificationsColumn is the table column denoting the notifications relation/edge.
	NotificationsColumn = "incident_notifications"
)

// Columns holds all SQL columns for incident fields.
var Columns = []string{
	FieldID,
	FieldNumber,
	FieldTitle,
	FieldSeverity,
	FieldStatus,
	FieldPriority,
	FieldSummary,
	FieldEscalatedCount,
	FieldCurrentLevel,
	FieldMergedInto,
	FieldTriggerType,
	FieldTriggerSourceEventID,
	FieldResolvedAt,
	FieldPostmortemSkipped,
	FieldAckedAt,
	FieldClosedAt,
	FieldEmbedding,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "incidents"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"escalation_policy_incidents",
	"incident_assignee",
	"service_incidents",
	"team_incidents",
}

var (
	// RespondersPrimaryKey and RespondersColumn2 are the table columns denoting the
	// primary key for the responders relation (M2M).
	RespondersPrimaryKey = []string{"incident_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultEscalatedCount holds the default value on creation for the "escalated_count" field.
	DefaultEscalatedCount int
	// DefaultCurrentLevel holds the default value on creation for the "current_level" field.
	DefaultCurrentLevel int
	// DefaultPostmortemSkipped holds the default value on creation for the "postmortem_skipped" field.
	DefaultPostmortemSkipped bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Severity defines the type for the "severity" enum field.
type Severity string

// Severity values.
const (
	SeverityCritical Severity = "critical"
	SeverityWarning  Severity = "warning"
	SeverityInfo     Severity = "info"
)

func (s Severity) String() string {
	return string(s)
}

// SeverityValidator is a validator for the "severity" field enum values. It is called by the builders before save.
func SeverityValidator(s Severity) error {
	switch s {
	case SeverityCritical, SeverityWarning, SeverityInfo:
		return nil
	default:
		return fmt.Errorf("incident: invalid enum value for severity field: %q", s)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusTriggered is the default value of the Status enum.
const DefaultStatus = StatusTriggered

// Status values.
const (
	StatusTriggered Status = "triggered"
	StatusEscalated Status = "escalated"
	StatusAcked     Status = "acked"
	StatusResolved  Status = "resolved"
	StatusClosed    Status = "closed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusTriggered, StatusEscalated, StatusAcked, StatusResolved, StatusClosed:
		return nil
	default:
		return fmt.Errorf("incident: invalid enum value for status field: %q", s)
	}
}

// Priority defines the type for the "priority" enum field.
type Priority string

// PriorityP3 is the default value of the Priority enum.
const DefaultPriority = PriorityP3

// Priority values.
const (
	PriorityP1 Priority = "p1"
	PriorityP2 Priority = "p2"
	PriorityP3 Priority = "p3"
	PriorityP4 Priority = "p4"
)

func (pr Priority) String() string {
	return string(pr)
}

// PriorityValidator is a validator for the "priority" field enum values. It is called by the builders before save.
func PriorityValidator(pr Priority) error {
	switch pr {
	case PriorityP1, PriorityP2, PriorityP3, PriorityP4:
		return nil
	default:
		return fmt.Errorf("incident: invalid enum value for priority field: %q", pr)
	}
}

// TriggerType defines the type for the "trigger_type" enum field.
type TriggerType string

// TriggerTypeAuto is the default value of the TriggerType enum.
const DefaultTriggerType = TriggerTypeAuto

// TriggerType values.
const (
	TriggerTypeAuto   TriggerType = "auto"
	TriggerTypeManual TriggerType = "manual"
	TriggerTypeMerged TriggerType = "merged"
)

func (tt TriggerType) String() string {
	return string(tt)
}

// TriggerTypeValidator is a validator for the "trigger_type" field enum values. It is called by the builders before save.
func TriggerTypeValidator(tt TriggerType) error {
	switch tt {
	case TriggerTypeAuto, TriggerTypeManual, TriggerTypeMerged:
		return nil
	default:
		return fmt.Errorf("incident: invalid enum value for trigger_type field: %q", tt)
	}
}

// OrderOption defines the ordering options for the Incident queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByEscalatedCount orders the results by the escalated_count field.
func ByEscalatedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEscalatedCount, opts...).ToFunc()
}

// ByCurrentLevel orders the results by the current_level field.
func ByCurrentLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentLevel, opts...).ToFunc()
}

// ByMergedInto orders the results by the merged_into field.
func ByMergedInto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMergedInto, opts...).ToFunc()
}

// ByTriggerType orders the results by the trigger_type field.
func ByTriggerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerType, opts...).ToFunc()
}

// ByTriggerSourceEventID orders the results by the trigger_source_event_id field.
func ByTriggerSourceEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerSourceEventID, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByPostmortemSkipped orders the results by the postmortem_skipped field.
func ByPostmortemSkipped(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostmortemSkipped, opts...).ToFunc()
}

// ByAckedAt orders the results by the acked_at field.
func ByAckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAckedAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByEmbedding orders the results by the embedding field.
func ByEmbedding(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmbedding, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTeamField orders the results by team field.
func ByTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamStep(), sql.OrderByField(field, opts...))
	}
}

// ByServiceField orders the results by service field.
func ByServiceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newServiceStep(), sql.OrderByField(field, opts...))
	}
}

// ByEscalationPolicyField orders the results by escalation_policy field.
func ByEscalationPolicyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEscalationPolicyStep(), sql.OrderByField(field, opts...))
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAssigneeField orders the results by assignee field.
func ByAssigneeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssigneeStep(), sql.OrderByField(field, opts...))
	}
}

// ByRespondersCount orders the results by responders count.
func ByRespondersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRespondersStep(), opts...)
	}
}

// ByResponders orders the results by responders terms.
func ByResponders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRespondersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTimelineCount orders the results by timeline count.
func ByTimelineCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTimelineStep(), opts...)
	}
}

// ByTimeline orders the results by timeline terms.
func ByTimeline(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTimelineStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByActionsCount orders the results by actions count.
func ByActionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newActionsStep(), opts...)
	}
}

// ByActions orders the results by actions terms.
func ByActions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPostmortemField orders the results by postmortem field.
func ByPostmortemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPostmortemStep(), sql.OrderByField(field, opts...))
	}
}

// ByAiInsightsCount orders the results by ai_insights count.
func ByAiInsightsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAiInsightsStep(), opts...)
	}
}

// ByAiInsights orders the results by ai_insights terms.
func ByAiInsights(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAiInsightsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNotificationsCount orders the results by notifications count.
func ByNotificationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotificationsStep(), opts...)
	}
}

// ByNotifications orders the results by notifications terms.
func ByNotifications(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
	)
}
func newServiceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ServiceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ServiceTable, ServiceColumn),
	)
}
func newEscalationPolicyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EscalationPolicyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EscalationPolicyTable, EscalationPolicyColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, EventsTable, EventsColumn),
	)
}
func newAssigneeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssigneeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AssigneeTable, AssigneeColumn),
	)
}
func newRespondersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RespondersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, RespondersTable, RespondersPrimaryKey...),
	)
}
func newTimelineStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TimelineInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TimelineTable, TimelineColumn),
	)
}
func newActionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ActionsTable, ActionsColumn),
	)
}
func newPostmortemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PostmortemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, PostmortemTable, PostmortemColumn),
	)
}
func newAiInsightsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AiInsightsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AiInsightsTable, AiInsightsColumn),
	)
}
func newNotificationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotificationsTable, NotificationsColumn),
	)
}
