// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kevin/vigil/ent/escalationpolicy"
	"github.com/kevin/vigil/ent/schema"
	"github.com/kevin/vigil/ent/team"
)

// EscalationPolicy is the model entity for the EscalationPolicy schema.
type EscalationPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// RepeatTimes holds the value of the "repeat_times" field.
	RepeatTimes int `json:"repeat_times,omitempty"`
	// 有序升级层级
	Levels []schema.EscalationLevel `json:"levels,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EscalationPolicyQuery when eager-loading is set.
	Edges                    EscalationPolicyEdges `json:"edges"`
	team_escalation_policies *int
	selectValues             sql.SelectValues
}

// EscalationPolicyEdges holds the relations/edges for other nodes in the graph.
type EscalationPolicyEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// Services holds the value of the services edge.
	Services []*Service `json:"services,omitempty"`
	// Schedules holds the value of the schedules edge.
	Schedules []*Schedule `json:"schedules,omitempty"`
	// Incidents holds the value of the incidents edge.
	Incidents []*Incident `json:"incidents,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EscalationPolicyEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// ServicesOrErr returns the Services value or an error if the edge
// was not loaded in eager-loading.
func (e EscalationPolicyEdges) ServicesOrErr() ([]*Service, error) {
	if e.loadedTypes[1] {
		return e.Services, nil
	}
	return nil, &NotLoadedError{edge: "services"}
}

// SchedulesOrErr returns the Schedules value or an error if the edge
// was not loaded in eager-loading.
func (e EscalationPolicyEdges) SchedulesOrErr() ([]*Schedule, error) {
	if e.loadedTypes[2] {
		return e.Schedules, nil
	}
	return nil, &NotLoadedError{edge: "schedules"}
}

// IncidentsOrErr returns the Incidents value or an error if the edge
// was not loaded in eager-loading.
func (e EscalationPolicyEdges) IncidentsOrErr() ([]*Incident, error) {
	if e.loadedTypes[3] {
		return e.Incidents, nil
	}
	return nil, &NotLoadedError{edge: "incidents"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EscalationPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case escalationpolicy.FieldLevels:
			values[i] = new([]byte)
		case escalationpolicy.FieldID, escalationpolicy.FieldRepeatTimes:
			values[i] = new(sql.NullInt64)
		case escalationpolicy.FieldName:
			values[i] = new(sql.NullString)
		case escalationpolicy.FieldCreatedAt, escalationpolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case escalationpolicy.ForeignKeys[0]: // team_escalation_policies
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EscalationPolicy fields.
func (_m *EscalationPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case escalationpolicy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case escalationpolicy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case escalationpolicy.FieldRepeatTimes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field repeat_times", values[i])
			} else if value.Valid {
				_m.RepeatTimes = int(value.Int64)
			}
		case escalationpolicy.FieldLevels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field levels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Levels); err != nil {
					return fmt.Errorf("unmarshal field levels: %w", err)
				}
			}
		case escalationpolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case escalationpolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case escalationpolicy.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field team_escalation_policies", value)
			} else if value.Valid {
				_m.team_escalation_policies = new(int)
				*_m.team_escalation_policies = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EscalationPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *EscalationPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the EscalationPolicy entity.
func (_m *EscalationPolicy) QueryTeam() *TeamQuery {
	return NewEscalationPolicyClient(_m.config).QueryTeam(_m)
}

// QueryServices queries the "services" edge of the EscalationPolicy entity.
func (_m *EscalationPolicy) QueryServices() *ServiceQuery {
	return NewEscalationPolicyClient(_m.config).QueryServices(_m)
}

// QuerySchedules queries the "schedules" edge of the EscalationPolicy entity.
func (_m *EscalationPolicy) QuerySchedules() *ScheduleQuery {
	return NewEscalationPolicyClient(_m.config).QuerySchedules(_m)
}

// QueryIncidents queries the "incidents" edge of the EscalationPolicy entity.
func (_m *EscalationPolicy) QueryIncidents() *IncidentQuery {
	return NewEscalationPolicyClient(_m.config).QueryIncidents(_m)
}

// Update returns a builder for updating this EscalationPolicy.
// Note that you need to call EscalationPolicy.Unwrap() before calling this method if this EscalationPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EscalationPolicy) Update() *EscalationPolicyUpdateOne {
	return NewEscalationPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EscalationPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EscalationPolicy) Unwrap() *EscalationPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EscalationPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EscalationPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("EscalationPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("repeat_times=")
	builder.WriteString(fmt.Sprintf("%v", _m.RepeatTimes))
	builder.WriteString(", ")
	builder.WriteString("levels=")
	builder.WriteString(fmt.Sprintf("%v", _m.Levels))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// EscalationPolicies is a parsable slice of EscalationPolicy.
type EscalationPolicies []*EscalationPolicy
