// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevin/vigil/ent/imaccountbinding"
	"github.com/kevin/vigil/ent/predicate"
)

// IMAccountBindingDelete is the builder for deleting a IMAccountBinding entity.
type IMAccountBindingDelete struct {
	config
	hooks    []Hook
	mutation *IMAccountBindingMutation
}

// Where appends a list predicates to the IMAccountBindingDelete builder.
func (_d *IMAccountBindingDelete) Where(ps ...predicate.IMAccountBinding) *IMAccountBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *IMAccountBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IMAccountBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *IMAccountBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(imaccountbinding.Table, sqlgraph.NewFieldSpec(imaccountbinding.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// IMAccountBindingDeleteOne is the builder for deleting a single IMAccountBinding entity.
type IMAccountBindingDeleteOne struct {
	_d *IMAccountBindingDelete
}

// Where appends a list predicates to the IMAccountBindingDelete builder.
func (_d *IMAccountBindingDeleteOne) Where(ps ...predicate.IMAccountBinding) *IMAccountBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *IMAccountBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{imaccountbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IMAccountBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
