// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevin/vigil/ent/incident"
	"github.com/kevin/vigil/ent/incidentaction"
)

// IncidentActionCreate is the builder for creating a IncidentAction entity.
type IncidentActionCreate struct {
	config
	mutation *IncidentActionMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *IncidentActionCreate) SetType(v incidentaction.Type) *IncidentActionCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetActor sets the "actor" field.
func (_c *IncidentActionCreate) SetActor(v map[string]string) *IncidentActionCreate {
	_c.mutation.SetActor(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *IncidentActionCreate) SetPayload(v map[string]interface{}) *IncidentActionCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetVia sets the "via" field.
func (_c *IncidentActionCreate) SetVia(v incidentaction.Via) *IncidentActionCreate {
	_c.mutation.SetVia(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *IncidentActionCreate) SetResult(v incidentaction.Result) *IncidentActionCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *IncidentActionCreate) SetNillableResult(v *incidentaction.Result) *IncidentActionCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *IncidentActionCreate) SetTimestamp(v time.Time) *IncidentActionCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *IncidentActionCreate) SetNillableTimestamp(v *time.Time) *IncidentActionCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetIncidentID sets the "incident" edge to the Incident entity by ID.
func (_c *IncidentActionCreate) SetIncidentID(id int) *IncidentActionCreate {
	_c.mutation.SetIncidentID(id)
	return _c
}

// SetNillableIncidentID sets the "incident" edge to the Incident entity by ID if the given value is not nil.
func (_c *IncidentActionCreate) SetNillableIncidentID(id *int) *IncidentActionCreate {
	if id != nil {
		_c = _c.SetIncidentID(*id)
	}
	return _c
}

// SetIncident sets the "incident" edge to the Incident entity.
func (_c *IncidentActionCreate) SetIncident(v *Incident) *IncidentActionCreate {
	return _c.SetIncidentID(v.ID)
}

// Mutation returns the IncidentActionMutation object of the builder.
func (_c *IncidentActionCreate) Mutation() *IncidentActionMutation {
	return _c.mutation
}

// Save creates the IncidentAction in the database.
func (_c *IncidentActionCreate) Save(ctx context.Context) (*IncidentAction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IncidentActionCreate) SaveX(ctx context.Context) *IncidentAction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IncidentActionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IncidentActionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IncidentActionCreate) defaults() {
	if _, ok := _c.mutation.Result(); !ok {
		v := incidentaction.DefaultResult
		_c.mutation.SetResult(v)
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := incidentaction.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IncidentActionCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "IncidentAction.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := incidentaction.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "IncidentAction.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Actor(); !ok {
		return &ValidationError{Name: "actor", err: errors.New(`ent: missing required field "IncidentAction.actor"`)}
	}
	if _, ok := _c.mutation.Via(); !ok {
		return &ValidationError{Name: "via", err: errors.New(`ent: missing required field "IncidentAction.via"`)}
	}
	if v, ok := _c.mutation.Via(); ok {
		if err := incidentaction.ViaValidator(v); err != nil {
			return &ValidationError{Name: "via", err: fmt.Errorf(`ent: validator failed for field "IncidentAction.via": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "IncidentAction.result"`)}
	}
	if v, ok := _c.mutation.Result(); ok {
		if err := incidentaction.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "IncidentAction.result": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "IncidentAction.timestamp"`)}
	}
	return nil
}

func (_c *IncidentActionCreate) sqlSave(ctx context.Context) (*IncidentAction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IncidentActionCreate) createSpec() (*IncidentAction, *sqlgraph.CreateSpec) {
	var (
		_node = &IncidentAction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(incidentaction.Table, sqlgraph.NewFieldSpec(incidentaction.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(incidentaction.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Actor(); ok {
		_spec.SetField(incidentaction.FieldActor, field.TypeJSON, value)
		_node.Actor = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(incidentaction.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Via(); ok {
		_spec.SetField(incidentaction.FieldVia, field.TypeEnum, value)
		_node.Via = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(incidentaction.FieldResult, field.TypeEnum, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(incidentaction.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if nodes := _c.mutation.IncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   incidentaction.IncidentTable,
			Columns: []string{incidentaction.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.incident_actions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IncidentActionCreateBulk is the builder for creating many IncidentAction entities in bulk.
type IncidentActionCreateBulk struct {
	config
	err      error
	builders []*IncidentActionCreate
}

// Save creates the IncidentAction entities in the database.
func (_c *IncidentActionCreateBulk) Save(ctx context.Context) ([]*IncidentAction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IncidentAction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IncidentActionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IncidentActionCreateBulk) SaveX(ctx context.Context) []*IncidentAction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IncidentActionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IncidentActionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
