// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kevin/vigil/ent/incident"
	"github.com/kevin/vigil/ent/incidentaction"
)

// IncidentAction is the model entity for the IncidentAction schema.
type IncidentAction struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type incidentaction.Type `json:"type,omitempty"`
	// actor: kind + id
	Actor map[string]string `json:"actor,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Via holds the value of the "via" field.
	Via incidentaction.Via `json:"via,omitempty"`
	// Result holds the value of the "result" field.
	Result incidentaction.Result `json:"result,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IncidentActionQuery when eager-loading is set.
	Edges            IncidentActionEdges `json:"edges"`
	incident_actions *int
	selectValues     sql.SelectValues
}

// IncidentActionEdges holds the relations/edges for other nodes in the graph.
type IncidentActionEdges struct {
	// Incident holds the value of the incident edge.
	Incident *Incident `json:"incident,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// IncidentOrErr returns the Incident value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IncidentActionEdges) IncidentOrErr() (*Incident, error) {
	if e.Incident != nil {
		return e.Incident, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: incident.Label}
	}
	return nil, &NotLoadedError{edge: "incident"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IncidentAction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case incidentaction.FieldActor, incidentaction.FieldPayload:
			values[i] = new([]byte)
		case incidentaction.FieldID:
			values[i] = new(sql.NullInt64)
		case incidentaction.FieldType, incidentaction.FieldVia, incidentaction.FieldResult:
			values[i] = new(sql.NullString)
		case incidentaction.FieldTimestamp:
			values[i] = new(sql.NullTime)
		case incidentaction.ForeignKeys[0]: // incident_actions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IncidentAction fields.
func (_m *IncidentAction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case incidentaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case incidentaction.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = incidentaction.Type(value.String)
			}
		case incidentaction.FieldActor:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field actor", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Actor); err != nil {
					return fmt.Errorf("unmarshal field actor: %w", err)
				}
			}
		case incidentaction.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case incidentaction.FieldVia:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field via", values[i])
			} else if value.Valid {
				_m.Via = incidentaction.Via(value.String)
			}
		case incidentaction.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = incidentaction.Result(value.String)
			}
		case incidentaction.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case incidentaction.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field incident_actions", value)
			} else if value.Valid {
				_m.incident_actions = new(int)
				*_m.incident_actions = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IncidentAction.
// This includes values selected through modifiers, order, etc.
func (_m *IncidentAction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIncident queries the "incident" edge of the IncidentAction entity.
func (_m *IncidentAction) QueryIncident() *IncidentQuery {
	return NewIncidentActionClient(_m.config).QueryIncident(_m)
}

// Update returns a builder for updating this IncidentAction.
// Note that you need to call IncidentAction.Unwrap() before calling this method if this IncidentAction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IncidentAction) Update() *IncidentActionUpdateOne {
	return NewIncidentActionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IncidentAction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IncidentAction) Unwrap() *IncidentAction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IncidentAction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IncidentAction) String() string {
	var builder strings.Builder
	builder.WriteString("IncidentAction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("actor=")
	builder.WriteString(fmt.Sprintf("%v", _m.Actor))
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("via=")
	builder.WriteString(fmt.Sprintf("%v", _m.Via))
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(fmt.Sprintf("%v", _m.Result))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IncidentActions is a parsable slice of IncidentAction.
type IncidentActions []*IncidentAction
