// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevin/vigil/ent/notificationrule"
	"github.com/kevin/vigil/ent/team"
)

// NotificationRuleCreate is the builder for creating a NotificationRule entity.
type NotificationRuleCreate struct {
	config
	mutation *NotificationRuleMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *NotificationRuleCreate) SetName(v string) *NotificationRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCondition sets the "condition" field.
func (_c *NotificationRuleCreate) SetCondition(v map[string]interface{}) *NotificationRuleCreate {
	_c.mutation.SetCondition(v)
	return _c
}

// SetChannels sets the "channels" field.
func (_c *NotificationRuleCreate) SetChannels(v []string) *NotificationRuleCreate {
	_c.mutation.SetChannels(v)
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *NotificationRuleCreate) SetTemplateID(v string) *NotificationRuleCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableTemplateID(v *string) *NotificationRuleCreate {
	if v != nil {
		_c.SetTemplateID(*v)
	}
	return _c
}

// SetQuietHours sets the "quiet_hours" field.
func (_c *NotificationRuleCreate) SetQuietHours(v map[string]interface{}) *NotificationRuleCreate {
	_c.mutation.SetQuietHours(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NotificationRuleCreate) SetEnabled(v bool) *NotificationRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableEnabled(v *bool) *NotificationRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationRuleCreate) SetCreatedAt(v time.Time) *NotificationRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableCreatedAt(v *time.Time) *NotificationRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationRuleCreate) SetUpdatedAt(v time.Time) *NotificationRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableUpdatedAt(v *time.Time) *NotificationRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (_c *NotificationRuleCreate) SetTeamID(id int) *NotificationRuleCreate {
	_c.mutation.SetTeamID(id)
	return _c
}

// SetNillableTeamID sets the "team" edge to the Team entity by ID if the given value is not nil.
func (_c *NotificationRuleCreate) SetNillableTeamID(id *int) *NotificationRuleCreate {
	if id != nil {
		_c = _c.SetTeamID(*id)
	}
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *NotificationRuleCreate) SetTeam(v *Team) *NotificationRuleCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the NotificationRuleMutation object of the builder.
func (_c *NotificationRuleCreate) Mutation() *NotificationRuleMutation {
	return _c.mutation
}

// Save creates the NotificationRule in the database.
func (_c *NotificationRuleCreate) Save(ctx context.Context) (*NotificationRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationRuleCreate) SaveX(ctx context.Context) *NotificationRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationRuleCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := notificationrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notificationrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := notificationrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationRuleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "NotificationRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := notificationrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Condition(); !ok {
		return &ValidationError{Name: "condition", err: errors.New(`ent: missing required field "NotificationRule.condition"`)}
	}
	if _, ok := _c.mutation.Channels(); !ok {
		return &ValidationError{Name: "channels", err: errors.New(`ent: missing required field "NotificationRule.channels"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NotificationRule.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationRule.updated_at"`)}
	}
	return nil
}

func (_c *NotificationRuleCreate) sqlSave(ctx context.Context) (*NotificationRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationRuleCreate) createSpec() (*NotificationRule, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationrule.Table, sqlgraph.NewFieldSpec(notificationrule.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(notificationrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Condition(); ok {
		_spec.SetField(notificationrule.FieldCondition, field.TypeJSON, value)
		_node.Condition = value
	}
	if value, ok := _c.mutation.Channels(); ok {
		_spec.SetField(notificationrule.FieldChannels, field.TypeJSON, value)
		_node.Channels = value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(notificationrule.FieldTemplateID, field.TypeString, value)
		_node.TemplateID = value
	}
	if value, ok := _c.mutation.QuietHours(); ok {
		_spec.SetField(notificationrule.FieldQuietHours, field.TypeJSON, value)
		_node.QuietHours = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(notificationrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationrule.TeamTable,
			Columns: []string{notificationrule.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.team_notification_rules = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationRuleCreateBulk is the builder for creating many NotificationRule entities in bulk.
type NotificationRuleCreateBulk struct {
	config
	err      error
	builders []*NotificationRuleCreate
}

// Save creates the NotificationRule entities in the database.
func (_c *NotificationRuleCreateBulk) Save(ctx context.Context) ([]*NotificationRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationRuleCreateBulk) SaveX(ctx context.Context) []*NotificationRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
