// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kevin/vigil/ent/incident"
	"github.com/kevin/vigil/ent/postmortem"
)

// Postmortem is the model entity for the Postmortem schema.
type Postmortem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status postmortem.Status `json:"status,omitempty"`
	// GeneratedBy holds the value of the "generated_by" field.
	GeneratedBy postmortem.GeneratedBy `json:"generated_by,omitempty"`
	// 结构化内容章节
	Sections map[string]interface{} `json:"sections,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostmortemQuery when eager-loading is set.
	Edges               PostmortemEdges `json:"edges"`
	incident_postmortem *int
	selectValues        sql.SelectValues
}

// PostmortemEdges holds the relations/edges for other nodes in the graph.
type PostmortemEdges struct {
	// Incident holds the value of the incident edge.
	Incident *Incident `json:"incident,omitempty"`
	// ActionItems holds the value of the action_items edge.
	ActionItems []*ActionItem `json:"action_items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// IncidentOrErr returns the Incident value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostmortemEdges) IncidentOrErr() (*Incident, error) {
	if e.Incident != nil {
		return e.Incident, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: incident.Label}
	}
	return nil, &NotLoadedError{edge: "incident"}
}

// ActionItemsOrErr returns the ActionItems value or an error if the edge
// was not loaded in eager-loading.
func (e PostmortemEdges) ActionItemsOrErr() ([]*ActionItem, error) {
	if e.loadedTypes[1] {
		return e.ActionItems, nil
	}
	return nil, &NotLoadedError{edge: "action_items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Postmortem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case postmortem.FieldSections:
			values[i] = new([]byte)
		case postmortem.FieldID:
			values[i] = new(sql.NullInt64)
		case postmortem.FieldStatus, postmortem.FieldGeneratedBy:
			values[i] = new(sql.NullString)
		case postmortem.FieldPublishedAt, postmortem.FieldCreatedAt, postmortem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case postmortem.ForeignKeys[0]: // incident_postmortem
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Postmortem fields.
func (_m *Postmortem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case postmortem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case postmortem.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = postmortem.Status(value.String)
			}
		case postmortem.FieldGeneratedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generated_by", values[i])
			} else if value.Valid {
				_m.GeneratedBy = postmortem.GeneratedBy(value.String)
			}
		case postmortem.FieldSections:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field sections", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Sections); err != nil {
					return fmt.Errorf("unmarshal field sections: %w", err)
				}
			}
		case postmortem.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case postmortem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case postmortem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case postmortem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field incident_postmortem", value)
			} else if value.Valid {
				_m.incident_postmortem = new(int)
				*_m.incident_postmortem = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Postmortem.
// This includes values selected through modifiers, order, etc.
func (_m *Postmortem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIncident queries the "incident" edge of the Postmortem entity.
func (_m *Postmortem) QueryIncident() *IncidentQuery {
	return NewPostmortemClient(_m.config).QueryIncident(_m)
}

// QueryActionItems queries the "action_items" edge of the Postmortem entity.
func (_m *Postmortem) QueryActionItems() *ActionItemQuery {
	return NewPostmortemClient(_m.config).QueryActionItems(_m)
}

// Update returns a builder for updating this Postmortem.
// Note that you need to call Postmortem.Unwrap() before calling this method if this Postmortem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Postmortem) Update() *PostmortemUpdateOne {
	return NewPostmortemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Postmortem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Postmortem) Unwrap() *Postmortem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Postmortem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Postmortem) String() string {
	var builder strings.Builder
	builder.WriteString("Postmortem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("generated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.GeneratedBy))
	builder.WriteString(", ")
	builder.WriteString("sections=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sections))
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Postmortems is a parsable slice of Postmortem.
type Postmortems []*Postmortem
