// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevin/vigil/ent/predicate"
	"github.com/kevin/vigil/ent/role"
	"github.com/kevin/vigil/ent/rolebinding"
	"github.com/kevin/vigil/ent/team"
	"github.com/kevin/vigil/ent/user"
)

// RoleBindingUpdate is the builder for updating RoleBinding entities.
type RoleBindingUpdate struct {
	config
	hooks    []Hook
	mutation *RoleBindingMutation
}

// Where appends a list predicates to the RoleBindingUpdate builder.
func (_u *RoleBindingUpdate) Where(ps ...predicate.RoleBinding) *RoleBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScopeLevel sets the "scope_level" field.
func (_u *RoleBindingUpdate) SetScopeLevel(v rolebinding.ScopeLevel) *RoleBindingUpdate {
	_u.mutation.SetScopeLevel(v)
	return _u
}

// SetNillableScopeLevel sets the "scope_level" field if the given value is not nil.
func (_u *RoleBindingUpdate) SetNillableScopeLevel(v *rolebinding.ScopeLevel) *RoleBindingUpdate {
	if v != nil {
		_u.SetScopeLevel(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *RoleBindingUpdate) SetTeamID(v string) *RoleBindingUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *RoleBindingUpdate) SetNillableTeamID(v *string) *RoleBindingUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *RoleBindingUpdate) ClearTeamID() *RoleBindingUpdate {
	_u.mutation.ClearTeamID()
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *RoleBindingUpdate) SetGrantedBy(v string) *RoleBindingUpdate {
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *RoleBindingUpdate) SetNillableGrantedBy(v *string) *RoleBindingUpdate {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (_u *RoleBindingUpdate) ClearGrantedBy() *RoleBindingUpdate {
	_u.mutation.ClearGrantedBy()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RoleBindingUpdate) SetExpiresAt(v time.Time) *RoleBindingUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RoleBindingUpdate) SetNillableExpiresAt(v *time.Time) *RoleBindingUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RoleBindingUpdate) ClearExpiresAt() *RoleBindingUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetSourceIncidentID sets the "source_incident_id" field.
func (_u *RoleBindingUpdate) SetSourceIncidentID(v int) *RoleBindingUpdate {
	_u.mutation.ResetSourceIncidentID()
	_u.mutation.SetSourceIncidentID(v)
	return _u
}

// SetNillableSourceIncidentID sets the "source_incident_id" field if the given value is not nil.
func (_u *RoleBindingUpdate) SetNillableSourceIncidentID(v *int) *RoleBindingUpdate {
	if v != nil {
		_u.SetSourceIncidentID(*v)
	}
	return _u
}

// AddSourceIncidentID adds value to the "source_incident_id" field.
func (_u *RoleBindingUpdate) AddSourceIncidentID(v int) *RoleBindingUpdate {
	_u.mutation.AddSourceIncidentID(v)
	return _u
}

// SetRoleID sets the "role" edge to the Role entity by ID.
func (_u *RoleBindingUpdate) SetRoleID(id int) *RoleBindingUpdate {
	_u.mutation.SetRoleID(id)
	return _u
}

// SetRole sets the "role" edge to the Role entity.
func (_u *RoleBindingUpdate) SetRole(v *Role) *RoleBindingUpdate {
	return _u.SetRoleID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *RoleBindingUpdate) SetUserID(id int) *RoleBindingUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RoleBindingUpdate) SetUser(v *User) *RoleBindingUpdate {
	return _u.SetUserID(v.ID)
}

// AddTeamIDs adds the "team" edge to the Team entity by IDs.
func (_u *RoleBindingUpdate) AddTeamIDs(ids ...int) *RoleBindingUpdate {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeam adds the "team" edges to the Team entity.
func (_u *RoleBindingUpdate) AddTeam(v ...*Team) *RoleBindingUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// Mutation returns the RoleBindingMutation object of the builder.
func (_u *RoleBindingUpdate) Mutation() *RoleBindingMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *RoleBindingUpdate) ClearRole() *RoleBindingUpdate {
	_u.mutation.ClearRole()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RoleBindingUpdate) ClearUser() *RoleBindingUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeam clears all "team" edges to the Team entity.
func (_u *RoleBindingUpdate) ClearTeam() *RoleBindingUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// RemoveTeamIDs removes the "team" edge to Team entities by IDs.
func (_u *RoleBindingUpdate) RemoveTeamIDs(ids ...int) *RoleBindingUpdate {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeam removes "team" edges to Team entities.
func (_u *RoleBindingUpdate) RemoveTeam(v ...*Team) *RoleBindingUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoleBindingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoleBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoleBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoleBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoleBindingUpdate) check() error {
	if v, ok := _u.mutation.ScopeLevel(); ok {
		if err := rolebinding.ScopeLevelValidator(v); err != nil {
			return &ValidationError{Name: "scope_level", err: fmt.Errorf(`ent: validator failed for field "RoleBinding.scope_level": %w`, err)}
		}
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoleBinding.role"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoleBinding.user"`)
	}
	return nil
}

func (_u *RoleBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolebinding.Table, rolebinding.Columns, sqlgraph.NewFieldSpec(rolebinding.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScopeLevel(); ok {
		_spec.SetField(rolebinding.FieldScopeLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TeamID(); ok {
		_spec.SetField(rolebinding.FieldTeamID, field.TypeString, value)
	}
	if _u.mutation.TeamIDCleared() {
		_spec.ClearField(rolebinding.FieldTeamID, field.TypeString)
	}
	if value, ok := _u.mutation.GrantedBy(); ok {
		_spec.SetField(rolebinding.FieldGrantedBy, field.TypeString, value)
	}
	if _u.mutation.GrantedByCleared() {
		_spec.ClearField(rolebinding.FieldGrantedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(rolebinding.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(rolebinding.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceIncidentID(); ok {
		_spec.SetField(rolebinding.FieldSourceIncidentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceIncidentID(); ok {
		_spec.AddField(rolebinding.FieldSourceIncidentID, field.TypeInt, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolebinding.RoleTable,
			Columns: []string{rolebinding.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolebinding.RoleTable,
			Columns: []string{rolebinding.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolebinding.UserTable,
			Columns: []string{rolebinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolebinding.UserTable,
			Columns: []string{rolebinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   rolebinding.TeamTable,
			Columns: rolebinding.TeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamIDs(); len(nodes) > 0 && !_u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   rolebinding.TeamTable,
			Columns: rolebinding.TeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   rolebinding.TeamTable,
			Columns: rolebinding.TeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolebinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoleBindingUpdateOne is the builder for updating a single RoleBinding entity.
type RoleBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoleBindingMutation
}

// SetScopeLevel sets the "scope_level" field.
func (_u *RoleBindingUpdateOne) SetScopeLevel(v rolebinding.ScopeLevel) *RoleBindingUpdateOne {
	_u.mutation.SetScopeLevel(v)
	return _u
}

// SetNillableScopeLevel sets the "scope_level" field if the given value is not nil.
func (_u *RoleBindingUpdateOne) SetNillableScopeLevel(v *rolebinding.ScopeLevel) *RoleBindingUpdateOne {
	if v != nil {
		_u.SetScopeLevel(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *RoleBindingUpdateOne) SetTeamID(v string) *RoleBindingUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *RoleBindingUpdateOne) SetNillableTeamID(v *string) *RoleBindingUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *RoleBindingUpdateOne) ClearTeamID() *RoleBindingUpdateOne {
	_u.mutation.ClearTeamID()
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *RoleBindingUpdateOne) SetGrantedBy(v string) *RoleBindingUpdateOne {
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *RoleBindingUpdateOne) SetNillableGrantedBy(v *string) *RoleBindingUpdateOne {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (_u *RoleBindingUpdateOne) ClearGrantedBy() *RoleBindingUpdateOne {
	_u.mutation.ClearGrantedBy()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RoleBindingUpdateOne) SetExpiresAt(v time.Time) *RoleBindingUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RoleBindingUpdateOne) SetNillableExpiresAt(v *time.Time) *RoleBindingUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RoleBindingUpdateOne) ClearExpiresAt() *RoleBindingUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetSourceIncidentID sets the "source_incident_id" field.
func (_u *RoleBindingUpdateOne) SetSourceIncidentID(v int) *RoleBindingUpdateOne {
	_u.mutation.ResetSourceIncidentID()
	_u.mutation.SetSourceIncidentID(v)
	return _u
}

// SetNillableSourceIncidentID sets the "source_incident_id" field if the given value is not nil.
func (_u *RoleBindingUpdateOne) SetNillableSourceIncidentID(v *int) *RoleBindingUpdateOne {
	if v != nil {
		_u.SetSourceIncidentID(*v)
	}
	return _u
}

// AddSourceIncidentID adds value to the "source_incident_id" field.
func (_u *RoleBindingUpdateOne) AddSourceIncidentID(v int) *RoleBindingUpdateOne {
	_u.mutation.AddSourceIncidentID(v)
	return _u
}

// SetRoleID sets the "role" edge to the Role entity by ID.
func (_u *RoleBindingUpdateOne) SetRoleID(id int) *RoleBindingUpdateOne {
	_u.mutation.SetRoleID(id)
	return _u
}

// SetRole sets the "role" edge to the Role entity.
func (_u *RoleBindingUpdateOne) SetRole(v *Role) *RoleBindingUpdateOne {
	return _u.SetRoleID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *RoleBindingUpdateOne) SetUserID(id int) *RoleBindingUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RoleBindingUpdateOne) SetUser(v *User) *RoleBindingUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddTeamIDs adds the "team" edge to the Team entity by IDs.
func (_u *RoleBindingUpdateOne) AddTeamIDs(ids ...int) *RoleBindingUpdateOne {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeam adds the "team" edges to the Team entity.
func (_u *RoleBindingUpdateOne) AddTeam(v ...*Team) *RoleBindingUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// Mutation returns the RoleBindingMutation object of the builder.
func (_u *RoleBindingUpdateOne) Mutation() *RoleBindingMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *RoleBindingUpdateOne) ClearRole() *RoleBindingUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RoleBindingUpdateOne) ClearUser() *RoleBindingUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeam clears all "team" edges to the Team entity.
func (_u *RoleBindingUpdateOne) ClearTeam() *RoleBindingUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// RemoveTeamIDs removes the "team" edge to Team entities by IDs.
func (_u *RoleBindingUpdateOne) RemoveTeamIDs(ids ...int) *RoleBindingUpdateOne {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeam removes "team" edges to Team entities.
func (_u *RoleBindingUpdateOne) RemoveTeam(v ...*Team) *RoleBindingUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// Where appends a list predicates to the RoleBindingUpdate builder.
func (_u *RoleBindingUpdateOne) Where(ps ...predicate.RoleBinding) *RoleBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoleBindingUpdateOne) Select(field string, fields ...string) *RoleBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RoleBinding entity.
func (_u *RoleBindingUpdateOne) Save(ctx context.Context) (*RoleBinding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoleBindingUpdateOne) SaveX(ctx context.Context) *RoleBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoleBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoleBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoleBindingUpdateOne) check() error {
	if v, ok := _u.mutation.ScopeLevel(); ok {
		if err := rolebinding.ScopeLevelValidator(v); err != nil {
			return &ValidationError{Name: "scope_level", err: fmt.Errorf(`ent: validator failed for field "RoleBinding.scope_level": %w`, err)}
		}
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoleBinding.role"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoleBinding.user"`)
	}
	return nil
}

func (_u *RoleBindingUpdateOne) sqlSave(ctx context.Context) (_node *RoleBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolebinding.Table, rolebinding.Columns, sqlgraph.NewFieldSpec(rolebinding.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoleBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rolebinding.FieldID)
		for _, f := range fields {
			if !rolebinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rolebinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScopeLevel(); ok {
		_spec.SetField(rolebinding.FieldScopeLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TeamID(); ok {
		_spec.SetField(rolebinding.FieldTeamID, field.TypeString, value)
	}
	if _u.mutation.TeamIDCleared() {
		_spec.ClearField(rolebinding.FieldTeamID, field.TypeString)
	}
	if value, ok := _u.mutation.GrantedBy(); ok {
		_spec.SetField(rolebinding.FieldGrantedBy, field.TypeString, value)
	}
	if _u.mutation.GrantedByCleared() {
		_spec.ClearField(rolebinding.FieldGrantedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(rolebinding.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(rolebinding.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SourceIncidentID(); ok {
		_spec.SetField(rolebinding.FieldSourceIncidentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceIncidentID(); ok {
		_spec.AddField(rolebinding.FieldSourceIncidentID, field.TypeInt, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolebinding.RoleTable,
			Columns: []string{rolebinding.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolebinding.RoleTable,
			Columns: []string{rolebinding.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolebinding.UserTable,
			Columns: []string{rolebinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolebinding.UserTable,
			Columns: []string{rolebinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   rolebinding.TeamTable,
			Columns: rolebinding.TeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamIDs(); len(nodes) > 0 && !_u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   rolebinding.TeamTable,
			Columns: rolebinding.TeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   rolebinding.TeamTable,
			Columns: rolebinding.TeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RoleBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolebinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
