// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevin/vigil/ent/escalationpolicy"
	"github.com/kevin/vigil/ent/override"
	"github.com/kevin/vigil/ent/predicate"
	"github.com/kevin/vigil/ent/rotation"
	"github.com/kevin/vigil/ent/schedule"
	"github.com/kevin/vigil/ent/service"
	"github.com/kevin/vigil/ent/team"
)

// ScheduleQuery is the builder for querying Schedule entities.
type ScheduleQuery struct {
	config
	ctx                    *QueryContext
	order                  []schedule.OrderOption
	inters                 []Interceptor
	predicates             []predicate.Schedule
	withTeam               *TeamQuery
	withServices           *ServiceQuery
	withRotations          *RotationQuery
	withOverrides          *OverrideQuery
	withEscalationPolicies *EscalationPolicyQuery
	withFKs                bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScheduleQuery builder.
func (_q *ScheduleQuery) Where(ps ...predicate.Schedule) *ScheduleQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ScheduleQuery) Limit(limit int) *ScheduleQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ScheduleQuery) Offset(offset int) *ScheduleQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ScheduleQuery) Unique(unique bool) *ScheduleQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ScheduleQuery) Order(o ...schedule.OrderOption) *ScheduleQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTeam chains the current query on the "team" edge.
func (_q *ScheduleQuery) QueryTeam() *TeamQuery {
	query := (&TeamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(schedule.Table, schedule.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, schedule.TeamTable, schedule.TeamColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryServices chains the current query on the "services" edge.
func (_q *ScheduleQuery) QueryServices() *ServiceQuery {
	query := (&ServiceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(schedule.Table, schedule.FieldID, selector),
			sqlgraph.To(service.Table, service.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, schedule.ServicesTable, schedule.ServicesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRotations chains the current query on the "rotations" edge.
func (_q *ScheduleQuery) QueryRotations() *RotationQuery {
	query := (&RotationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(schedule.Table, schedule.FieldID, selector),
			sqlgraph.To(rotation.Table, rotation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, schedule.RotationsTable, schedule.RotationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOverrides chains the current query on the "overrides" edge.
func (_q *ScheduleQuery) QueryOverrides() *OverrideQuery {
	query := (&OverrideClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(schedule.Table, schedule.FieldID, selector),
			sqlgraph.To(override.Table, override.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, schedule.OverridesTable, schedule.OverridesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEscalationPolicies chains the current query on the "escalation_policies" edge.
func (_q *ScheduleQuery) QueryEscalationPolicies() *EscalationPolicyQuery {
	query := (&EscalationPolicyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(schedule.Table, schedule.FieldID, selector),
			sqlgraph.To(escalationpolicy.Table, escalationpolicy.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, schedule.EscalationPoliciesTable, schedule.EscalationPoliciesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Schedule entity from the query.
// Returns a *NotFoundError when no Schedule was found.
func (_q *ScheduleQuery) First(ctx context.Context) (*Schedule, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{schedule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ScheduleQuery) FirstX(ctx context.Context) *Schedule {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Schedule ID from the query.
// Returns a *NotFoundError when no Schedule ID was found.
func (_q *ScheduleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{schedule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ScheduleQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Schedule entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Schedule entity is found.
// Returns a *NotFoundError when no Schedule entities are found.
func (_q *ScheduleQuery) Only(ctx context.Context) (*Schedule, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{schedule.Label}
	default:
		return nil, &NotSingularError{schedule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ScheduleQuery) OnlyX(ctx context.Context) *Schedule {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Schedule ID in the query.
// Returns a *NotSingularError when more than one Schedule ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ScheduleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{schedule.Label}
	default:
		err = &NotSingularError{schedule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ScheduleQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Schedules.
func (_q *ScheduleQuery) All(ctx context.Context) ([]*Schedule, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Schedule, *ScheduleQuery]()
	return withInterceptors[[]*Schedule](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ScheduleQuery) AllX(ctx context.Context) []*Schedule {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Schedule IDs.
func (_q *ScheduleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(schedule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ScheduleQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ScheduleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ScheduleQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ScheduleQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ScheduleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ScheduleQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScheduleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ScheduleQuery) Clone() *ScheduleQuery {
	if _q == nil {
		return nil
	}
	return &ScheduleQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]schedule.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.Schedule{}, _q.predicates...),
		withTeam:               _q.withTeam.Clone(),
		withServices:           _q.withServices.Clone(),
		withRotations:          _q.withRotations.Clone(),
		withOverrides:          _q.withOverrides.Clone(),
		withEscalationPolicies: _q.withEscalationPolicies.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTeam tells the query-builder to eager-load the nodes that are connected to
// the "team" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ScheduleQuery) WithTeam(opts ...func(*TeamQuery)) *ScheduleQuery {
	query := (&TeamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeam = query
	return _q
}

// WithServices tells the query-builder to eager-load the nodes that are connected to
// the "services" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ScheduleQuery) WithServices(opts ...func(*ServiceQuery)) *ScheduleQuery {
	query := (&ServiceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withServices = query
	return _q
}

// WithRotations tells the query-builder to eager-load the nodes that are connected to
// the "rotations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ScheduleQuery) WithRotations(opts ...func(*RotationQuery)) *ScheduleQuery {
	query := (&RotationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRotations = query
	return _q
}

// WithOverrides tells the query-builder to eager-load the nodes that are connected to
// the "overrides" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ScheduleQuery) WithOverrides(opts ...func(*OverrideQuery)) *ScheduleQuery {
	query := (&OverrideClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOverrides = query
	return _q
}

// WithEscalationPolicies tells the query-builder to eager-load the nodes that are connected to
// the "escalation_policies" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ScheduleQuery) WithEscalationPolicies(opts ...func(*EscalationPolicyQuery)) *ScheduleQuery {
	query := (&EscalationPolicyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEscalationPolicies = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Schedule.Query().
//		GroupBy(schedule.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ScheduleQuery) GroupBy(field string, fields ...string) *ScheduleGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ScheduleGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = schedule.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Schedule.Query().
//		Select(schedule.FieldName).
//		Scan(ctx, &v)
func (_q *ScheduleQuery) Select(fields ...string) *ScheduleSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ScheduleSelect{ScheduleQuery: _q}
	sbuild.label = schedule.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ScheduleSelect configured with the given aggregations.
func (_q *ScheduleQuery) Aggregate(fns ...AggregateFunc) *ScheduleSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ScheduleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !schedule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ScheduleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Schedule, error) {
	var (
		nodes       = []*Schedule{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withTeam != nil,
			_q.withServices != nil,
			_q.withRotations != nil,
			_q.withOverrides != nil,
			_q.withEscalationPolicies != nil,
		}
	)
	if _q.withTeam != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, schedule.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Schedule).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Schedule{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTeam; query != nil {
		if err := _q.loadTeam(ctx, query, nodes, nil,
			func(n *Schedule, e *Team) { n.Edges.Team = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withServices; query != nil {
		if err := _q.loadServices(ctx, query, nodes,
			func(n *Schedule) { n.Edges.Services = []*Service{} },
			func(n *Schedule, e *Service) { n.Edges.Services = append(n.Edges.Services, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRotations; query != nil {
		if err := _q.loadRotations(ctx, query, nodes,
			func(n *Schedule) { n.Edges.Rotations = []*Rotation{} },
			func(n *Schedule, e *Rotation) { n.Edges.Rotations = append(n.Edges.Rotations, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOverrides; query != nil {
		if err := _q.loadOverrides(ctx, query, nodes,
			func(n *Schedule) { n.Edges.Overrides = []*Override{} },
			func(n *Schedule, e *Override) { n.Edges.Overrides = append(n.Edges.Overrides, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEscalationPolicies; query != nil {
		if err := _q.loadEscalationPolicies(ctx, query, nodes,
			func(n *Schedule) { n.Edges.EscalationPolicies = []*EscalationPolicy{} },
			func(n *Schedule, e *EscalationPolicy) {
				n.Edges.EscalationPolicies = append(n.Edges.EscalationPolicies, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ScheduleQuery) loadTeam(ctx context.Context, query *TeamQuery, nodes []*Schedule, init func(*Schedule), assign func(*Schedule, *Team)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Schedule)
	for i := range nodes {
		if nodes[i].team_schedules == nil {
			continue
		}
		fk := *nodes[i].team_schedules
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(team.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "team_schedules" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ScheduleQuery) loadServices(ctx context.Context, query *ServiceQuery, nodes []*Schedule, init func(*Schedule), assign func(*Schedule, *Service)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Schedule)
	nids := make(map[int]map[*Schedule]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(schedule.ServicesTable)
		s.Join(joinT).On(s.C(service.FieldID), joinT.C(schedule.ServicesPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(schedule.ServicesPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(schedule.ServicesPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Schedule]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Service](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "services" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *ScheduleQuery) loadRotations(ctx context.Context, query *RotationQuery, nodes []*Schedule, init func(*Schedule), assign func(*Schedule, *Rotation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Schedule)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Rotation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(schedule.RotationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.schedule_rotations
		if fk == nil {
			return fmt.Errorf(`foreign-key "schedule_rotations" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "schedule_rotations" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ScheduleQuery) loadOverrides(ctx context.Context, query *OverrideQuery, nodes []*Schedule, init func(*Schedule), assign func(*Schedule, *Override)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Schedule)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Override(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(schedule.OverridesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.schedule_overrides
		if fk == nil {
			return fmt.Errorf(`foreign-key "schedule_overrides" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "schedule_overrides" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ScheduleQuery) loadEscalationPolicies(ctx context.Context, query *EscalationPolicyQuery, nodes []*Schedule, init func(*Schedule), assign func(*Schedule, *EscalationPolicy)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Schedule)
	nids := make(map[int]map[*Schedule]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(schedule.EscalationPoliciesTable)
		s.Join(joinT).On(s.C(escalationpolicy.FieldID), joinT.C(schedule.EscalationPoliciesPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(schedule.EscalationPoliciesPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(schedule.EscalationPoliciesPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Schedule]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*EscalationPolicy](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "escalation_policies" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (_q *ScheduleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ScheduleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(schedule.Table, schedule.Columns, sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedule.FieldID)
		for i := range fields {
			if fields[i] != schedule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ScheduleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(schedule.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = schedule.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ScheduleGroupBy is the group-by builder for Schedule entities.
type ScheduleGroupBy struct {
	selector
	build *ScheduleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ScheduleGroupBy) Aggregate(fns ...AggregateFunc) *ScheduleGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ScheduleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScheduleQuery, *ScheduleGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ScheduleGroupBy) sqlScan(ctx context.Context, root *ScheduleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ScheduleSelect is the builder for selecting fields of Schedule entities.
type ScheduleSelect struct {
	*ScheduleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ScheduleSelect) Aggregate(fns ...AggregateFunc) *ScheduleSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ScheduleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScheduleQuery, *ScheduleSelect](ctx, _s.ScheduleQuery, _s, _s.inters, v)
}

func (_s *ScheduleSelect) sqlScan(ctx context.Context, root *ScheduleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
