// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/kevin/vigil/ent/predicate"
	"github.com/kevin/vigil/ent/service"
	"github.com/kevin/vigil/ent/subscription"
	"github.com/kevin/vigil/ent/team"
	"github.com/kevin/vigil/ent/user"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChannels sets the "channels" field.
func (_u *SubscriptionUpdate) SetChannels(v []string) *SubscriptionUpdate {
	_u.mutation.SetChannels(v)
	return _u
}

// AppendChannels appends value to the "channels" field.
func (_u *SubscriptionUpdate) AppendChannels(v []string) *SubscriptionUpdate {
	_u.mutation.AppendChannels(v)
	return _u
}

// ClearChannels clears the value of the "channels" field.
func (_u *SubscriptionUpdate) ClearChannels() *SubscriptionUpdate {
	_u.mutation.ClearChannels()
	return _u
}

// SetMinSeverity sets the "min_severity" field.
func (_u *SubscriptionUpdate) SetMinSeverity(v subscription.MinSeverity) *SubscriptionUpdate {
	_u.mutation.SetMinSeverity(v)
	return _u
}

// SetNillableMinSeverity sets the "min_severity" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableMinSeverity(v *subscription.MinSeverity) *SubscriptionUpdate {
	if v != nil {
		_u.SetMinSeverity(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdate) SetUpdatedAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SubscriptionUpdate) SetUserID(id int) *SubscriptionUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionUpdate) SetUser(v *User) *SubscriptionUpdate {
	return _u.SetUserID(v.ID)
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (_u *SubscriptionUpdate) SetTeamID(id int) *SubscriptionUpdate {
	_u.mutation.SetTeamID(id)
	return _u
}

// SetNillableTeamID sets the "team" edge to the Team entity by ID if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableTeamID(id *int) *SubscriptionUpdate {
	if id != nil {
		_u = _u.SetTeamID(*id)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *SubscriptionUpdate) SetTeam(v *Team) *SubscriptionUpdate {
	return _u.SetTeamID(v.ID)
}

// SetServiceID sets the "service" edge to the Service entity by ID.
func (_u *SubscriptionUpdate) SetServiceID(id int) *SubscriptionUpdate {
	_u.mutation.SetServiceID(id)
	return _u
}

// SetNillableServiceID sets the "service" edge to the Service entity by ID if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableServiceID(id *int) *SubscriptionUpdate {
	if id != nil {
		_u = _u.SetServiceID(*id)
	}
	return _u
}

// SetService sets the "service" edge to the Service entity.
func (_u *SubscriptionUpdate) SetService(v *Service) *SubscriptionUpdate {
	return _u.SetServiceID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionUpdate) ClearUser() *SubscriptionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *SubscriptionUpdate) ClearTeam() *SubscriptionUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearService clears the "service" edge to the Service entity.
func (_u *SubscriptionUpdate) ClearService() *SubscriptionUpdate {
	_u.mutation.ClearService()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdate) check() error {
	if v, ok := _u.mutation.MinSeverity(); ok {
		if err := subscription.MinSeverityValidator(v); err != nil {
			return &ValidationError{Name: "min_severity", err: fmt.Errorf(`ent: validator failed for field "Subscription.min_severity": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subscription.user"`)
	}
	return nil
}

func (_u *SubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Channels(); ok {
		_spec.SetField(subscription.FieldChannels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChannels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, subscription.FieldChannels, value)
		})
	}
	if _u.mutation.ChannelsCleared() {
		_spec.ClearField(subscription.FieldChannels, field.TypeJSON)
	}
	if value, ok := _u.mutation.MinSeverity(); ok {
		_spec.SetField(subscription.FieldMinSeverity, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.TeamTable,
			Columns: []string{subscription.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.TeamTable,
			Columns: []string{subscription.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.ServiceTable,
			Columns: []string{subscription.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.ServiceTable,
			Columns: []string{subscription.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetChannels sets the "channels" field.
func (_u *SubscriptionUpdateOne) SetChannels(v []string) *SubscriptionUpdateOne {
	_u.mutation.SetChannels(v)
	return _u
}

// AppendChannels appends value to the "channels" field.
func (_u *SubscriptionUpdateOne) AppendChannels(v []string) *SubscriptionUpdateOne {
	_u.mutation.AppendChannels(v)
	return _u
}

// ClearChannels clears the value of the "channels" field.
func (_u *SubscriptionUpdateOne) ClearChannels() *SubscriptionUpdateOne {
	_u.mutation.ClearChannels()
	return _u
}

// SetMinSeverity sets the "min_severity" field.
func (_u *SubscriptionUpdateOne) SetMinSeverity(v subscription.MinSeverity) *SubscriptionUpdateOne {
	_u.mutation.SetMinSeverity(v)
	return _u
}

// SetNillableMinSeverity sets the "min_severity" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableMinSeverity(v *subscription.MinSeverity) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetMinSeverity(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *SubscriptionUpdateOne) SetUserID(id int) *SubscriptionUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionUpdateOne) SetUser(v *User) *SubscriptionUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (_u *SubscriptionUpdateOne) SetTeamID(id int) *SubscriptionUpdateOne {
	_u.mutation.SetTeamID(id)
	return _u
}

// SetNillableTeamID sets the "team" edge to the Team entity by ID if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableTeamID(id *int) *SubscriptionUpdateOne {
	if id != nil {
		_u = _u.SetTeamID(*id)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *SubscriptionUpdateOne) SetTeam(v *Team) *SubscriptionUpdateOne {
	return _u.SetTeamID(v.ID)
}

// SetServiceID sets the "service" edge to the Service entity by ID.
func (_u *SubscriptionUpdateOne) SetServiceID(id int) *SubscriptionUpdateOne {
	_u.mutation.SetServiceID(id)
	return _u
}

// SetNillableServiceID sets the "service" edge to the Service entity by ID if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableServiceID(id *int) *SubscriptionUpdateOne {
	if id != nil {
		_u = _u.SetServiceID(*id)
	}
	return _u
}

// SetService sets the "service" edge to the Service entity.
func (_u *SubscriptionUpdateOne) SetService(v *Service) *SubscriptionUpdateOne {
	return _u.SetServiceID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionUpdateOne) ClearUser() *SubscriptionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *SubscriptionUpdateOne) ClearTeam() *SubscriptionUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearService clears the "service" edge to the Service entity.
func (_u *SubscriptionUpdateOne) ClearService() *SubscriptionUpdateOne {
	_u.mutation.ClearService()
	return _u
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subscription entity.
func (_u *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.MinSeverity(); ok {
		if err := subscription.MinSeverityValidator(v); err != nil {
			return &ValidationError{Name: "min_severity", err: fmt.Errorf(`ent: validator failed for field "Subscription.min_severity": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subscription.user"`)
	}
	return nil
}

func (_u *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Channels(); ok {
		_spec.SetField(subscription.FieldChannels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChannels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, subscription.FieldChannels, value)
		})
	}
	if _u.mutation.ChannelsCleared() {
		_spec.ClearField(subscription.FieldChannels, field.TypeJSON)
	}
	if value, ok := _u.mutation.MinSeverity(); ok {
		_spec.SetField(subscription.FieldMinSeverity, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.UserTable,
			Columns: []string{subscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.TeamTable,
			Columns: []string{subscription.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.TeamTable,
			Columns: []string{subscription.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.ServiceTable,
			Columns: []string{subscription.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.ServiceTable,
			Columns: []string{subscription.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
