// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kevin/vigil/ent/suppressionrule"
	"github.com/kevin/vigil/ent/team"
)

// SuppressionRule is the model entity for the SuppressionRule schema.
type SuppressionRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// label 匹配条件，全等匹配
	MatchLabels map[string]string `json:"match_labels,omitempty"`
	// 时间窗口，空=无限制
	TimeWindow map[string]interface{} `json:"time_window,omitempty"`
	// 命中的严重度，空=所有
	SeverityFilter []string `json:"severity_filter,omitempty"`
	// Action holds the value of the "action" field.
	Action suppressionrule.Action `json:"action,omitempty"`
	// 降级目标严重度
	ReduceTo string `json:"reduce_to,omitempty"`
	// critical 不被抑制
	PreserveCritical bool `json:"preserve_critical,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// 规则来源：manual 人工 / ai 由采纳的降噪建议沉淀
	Source suppressionrule.Source `json:"source,omitempty"`
	// 沉淀本规则的 AIInsight id（幂等键，source=ai 时有值）
	SourceInsightID int `json:"source_insight_id,omitempty"`
	// 规则过期时间
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SuppressionRuleQuery when eager-loading is set.
	Edges                  SuppressionRuleEdges `json:"edges"`
	team_suppression_rules *int
	selectValues           sql.SelectValues
}

// SuppressionRuleEdges holds the relations/edges for other nodes in the graph.
type SuppressionRuleEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SuppressionRuleEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SuppressionRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case suppressionrule.FieldMatchLabels, suppressionrule.FieldTimeWindow, suppressionrule.FieldSeverityFilter:
			values[i] = new([]byte)
		case suppressionrule.FieldPreserveCritical, suppressionrule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case suppressionrule.FieldID, suppressionrule.FieldSourceInsightID:
			values[i] = new(sql.NullInt64)
		case suppressionrule.FieldName, suppressionrule.FieldAction, suppressionrule.FieldReduceTo, suppressionrule.FieldSource:
			values[i] = new(sql.NullString)
		case suppressionrule.FieldExpiresAt, suppressionrule.FieldCreatedAt, suppressionrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case suppressionrule.ForeignKeys[0]: // team_suppression_rules
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SuppressionRule fields.
func (_m *SuppressionRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case suppressionrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case suppressionrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case suppressionrule.FieldMatchLabels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field match_labels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MatchLabels); err != nil {
					return fmt.Errorf("unmarshal field match_labels: %w", err)
				}
			}
		case suppressionrule.FieldTimeWindow:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field time_window", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TimeWindow); err != nil {
					return fmt.Errorf("unmarshal field time_window: %w", err)
				}
			}
		case suppressionrule.FieldSeverityFilter:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field severity_filter", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SeverityFilter); err != nil {
					return fmt.Errorf("unmarshal field severity_filter: %w", err)
				}
			}
		case suppressionrule.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = suppressionrule.Action(value.String)
			}
		case suppressionrule.FieldReduceTo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reduce_to", values[i])
			} else if value.Valid {
				_m.ReduceTo = value.String
			}
		case suppressionrule.FieldPreserveCritical:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field preserve_critical", values[i])
			} else if value.Valid {
				_m.PreserveCritical = value.Bool
			}
		case suppressionrule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case suppressionrule.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = suppressionrule.Source(value.String)
			}
		case suppressionrule.FieldSourceInsightID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_insight_id", values[i])
			} else if value.Valid {
				_m.SourceInsightID = int(value.Int64)
			}
		case suppressionrule.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case suppressionrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case suppressionrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case suppressionrule.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field team_suppression_rules", value)
			} else if value.Valid {
				_m.team_suppression_rules = new(int)
				*_m.team_suppression_rules = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SuppressionRule.
// This includes values selected through modifiers, order, etc.
func (_m *SuppressionRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the SuppressionRule entity.
func (_m *SuppressionRule) QueryTeam() *TeamQuery {
	return NewSuppressionRuleClient(_m.config).QueryTeam(_m)
}

// Update returns a builder for updating this SuppressionRule.
// Note that you need to call SuppressionRule.Unwrap() before calling this method if this SuppressionRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SuppressionRule) Update() *SuppressionRuleUpdateOne {
	return NewSuppressionRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SuppressionRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SuppressionRule) Unwrap() *SuppressionRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SuppressionRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SuppressionRule) String() string {
	var builder strings.Builder
	builder.WriteString("SuppressionRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("match_labels=")
	builder.WriteString(fmt.Sprintf("%v", _m.MatchLabels))
	builder.WriteString(", ")
	builder.WriteString("time_window=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeWindow))
	builder.WriteString(", ")
	builder.WriteString("severity_filter=")
	builder.WriteString(fmt.Sprintf("%v", _m.SeverityFilter))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", _m.Action))
	builder.WriteString(", ")
	builder.WriteString("reduce_to=")
	builder.WriteString(_m.ReduceTo)
	builder.WriteString(", ")
	builder.WriteString("preserve_critical=")
	builder.WriteString(fmt.Sprintf("%v", _m.PreserveCritical))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("source_insight_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceInsightID))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SuppressionRules is a parsable slice of SuppressionRule.
type SuppressionRules []*SuppressionRule
