// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevin/vigil/ent/suppressionrule"
	"github.com/kevin/vigil/ent/team"
)

// SuppressionRuleCreate is the builder for creating a SuppressionRule entity.
type SuppressionRuleCreate struct {
	config
	mutation *SuppressionRuleMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SuppressionRuleCreate) SetName(v string) *SuppressionRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *SuppressionRuleCreate) SetKind(v suppressionrule.Kind) *SuppressionRuleCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillableKind(v *suppressionrule.Kind) *SuppressionRuleCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetMatchLabels sets the "match_labels" field.
func (_c *SuppressionRuleCreate) SetMatchLabels(v map[string]string) *SuppressionRuleCreate {
	_c.mutation.SetMatchLabels(v)
	return _c
}

// SetTimeWindow sets the "time_window" field.
func (_c *SuppressionRuleCreate) SetTimeWindow(v map[string]interface{}) *SuppressionRuleCreate {
	_c.mutation.SetTimeWindow(v)
	return _c
}

// SetSeverityFilter sets the "severity_filter" field.
func (_c *SuppressionRuleCreate) SetSeverityFilter(v []string) *SuppressionRuleCreate {
	_c.mutation.SetSeverityFilter(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *SuppressionRuleCreate) SetAction(v suppressionrule.Action) *SuppressionRuleCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillableAction(v *suppressionrule.Action) *SuppressionRuleCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetReduceTo sets the "reduce_to" field.
func (_c *SuppressionRuleCreate) SetReduceTo(v string) *SuppressionRuleCreate {
	_c.mutation.SetReduceTo(v)
	return _c
}

// SetNillableReduceTo sets the "reduce_to" field if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillableReduceTo(v *string) *SuppressionRuleCreate {
	if v != nil {
		_c.SetReduceTo(*v)
	}
	return _c
}

// SetPreserveCritical sets the "preserve_critical" field.
func (_c *SuppressionRuleCreate) SetPreserveCritical(v bool) *SuppressionRuleCreate {
	_c.mutation.SetPreserveCritical(v)
	return _c
}

// SetNillablePreserveCritical sets the "preserve_critical" field if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillablePreserveCritical(v *bool) *SuppressionRuleCreate {
	if v != nil {
		_c.SetPreserveCritical(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SuppressionRuleCreate) SetEnabled(v bool) *SuppressionRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillableEnabled(v *bool) *SuppressionRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *SuppressionRuleCreate) SetSource(v suppressionrule.Source) *SuppressionRuleCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillableSource(v *suppressionrule.Source) *SuppressionRuleCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSourceInsightID sets the "source_insight_id" field.
func (_c *SuppressionRuleCreate) SetSourceInsightID(v int) *SuppressionRuleCreate {
	_c.mutation.SetSourceInsightID(v)
	return _c
}

// SetNillableSourceInsightID sets the "source_insight_id" field if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillableSourceInsightID(v *int) *SuppressionRuleCreate {
	if v != nil {
		_c.SetSourceInsightID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SuppressionRuleCreate) SetExpiresAt(v time.Time) *SuppressionRuleCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillableExpiresAt(v *time.Time) *SuppressionRuleCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SuppressionRuleCreate) SetCreatedAt(v time.Time) *SuppressionRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillableCreatedAt(v *time.Time) *SuppressionRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SuppressionRuleCreate) SetUpdatedAt(v time.Time) *SuppressionRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillableUpdatedAt(v *time.Time) *SuppressionRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTeamID sets the "team" edge to the Team entity by ID.
func (_c *SuppressionRuleCreate) SetTeamID(id int) *SuppressionRuleCreate {
	_c.mutation.SetTeamID(id)
	return _c
}

// SetNillableTeamID sets the "team" edge to the Team entity by ID if the given value is not nil.
func (_c *SuppressionRuleCreate) SetNillableTeamID(id *int) *SuppressionRuleCreate {
	if id != nil {
		_c = _c.SetTeamID(*id)
	}
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *SuppressionRuleCreate) SetTeam(v *Team) *SuppressionRuleCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the SuppressionRuleMutation object of the builder.
func (_c *SuppressionRuleCreate) Mutation() *SuppressionRuleMutation {
	return _c.mutation
}

// Save creates the SuppressionRule in the database.
func (_c *SuppressionRuleCreate) Save(ctx context.Context) (*SuppressionRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SuppressionRuleCreate) SaveX(ctx context.Context) *SuppressionRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SuppressionRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SuppressionRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SuppressionRuleCreate) defaults() {
	if _, ok := _c.mutation.Kind(); !ok {
		v := suppressionrule.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.Action(); !ok {
		v := suppressionrule.DefaultAction
		_c.mutation.SetAction(v)
	}
	if _, ok := _c.mutation.PreserveCritical(); !ok {
		v := suppressionrule.DefaultPreserveCritical
		_c.mutation.SetPreserveCritical(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := suppressionrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := suppressionrule.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := suppressionrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := suppressionrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SuppressionRuleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SuppressionRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := suppressionrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SuppressionRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "SuppressionRule.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := suppressionrule.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SuppressionRule.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MatchLabels(); !ok {
		return &ValidationError{Name: "match_labels", err: errors.New(`ent: missing required field "SuppressionRule.match_labels"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "SuppressionRule.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := suppressionrule.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SuppressionRule.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PreserveCritical(); !ok {
		return &ValidationError{Name: "preserve_critical", err: errors.New(`ent: missing required field "SuppressionRule.preserve_critical"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "SuppressionRule.enabled"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "SuppressionRule.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := suppressionrule.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SuppressionRule.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SuppressionRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SuppressionRule.updated_at"`)}
	}
	return nil
}

func (_c *SuppressionRuleCreate) sqlSave(ctx context.Context) (*SuppressionRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SuppressionRuleCreate) createSpec() (*SuppressionRule, *sqlgraph.CreateSpec) {
	var (
		_node = &SuppressionRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(suppressionrule.Table, sqlgraph.NewFieldSpec(suppressionrule.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(suppressionrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(suppressionrule.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.MatchLabels(); ok {
		_spec.SetField(suppressionrule.FieldMatchLabels, field.TypeJSON, value)
		_node.MatchLabels = value
	}
	if value, ok := _c.mutation.TimeWindow(); ok {
		_spec.SetField(suppressionrule.FieldTimeWindow, field.TypeJSON, value)
		_node.TimeWindow = value
	}
	if value, ok := _c.mutation.SeverityFilter(); ok {
		_spec.SetField(suppressionrule.FieldSeverityFilter, field.TypeJSON, value)
		_node.SeverityFilter = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(suppressionrule.FieldAction, field.TypeEnum, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.ReduceTo(); ok {
		_spec.SetField(suppressionrule.FieldReduceTo, field.TypeString, value)
		_node.ReduceTo = value
	}
	if value, ok := _c.mutation.PreserveCritical(); ok {
		_spec.SetField(suppressionrule.FieldPreserveCritical, field.TypeBool, value)
		_node.PreserveCritical = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(suppressionrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(suppressionrule.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceInsightID(); ok {
		_spec.SetField(suppressionrule.FieldSourceInsightID, field.TypeInt, value)
		_node.SourceInsightID = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(suppressionrule.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(suppressionrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(suppressionrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   suppressionrule.TeamTable,
			Columns: []string{suppressionrule.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.team_suppression_rules = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SuppressionRuleCreateBulk is the builder for creating many SuppressionRule entities in bulk.
type SuppressionRuleCreateBulk struct {
	config
	err      error
	builders []*SuppressionRuleCreate
}

// Save creates the SuppressionRule entities in the database.
func (_c *SuppressionRuleCreateBulk) Save(ctx context.Context) ([]*SuppressionRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SuppressionRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SuppressionRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SuppressionRuleCreateBulk) SaveX(ctx context.Context) []*SuppressionRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SuppressionRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SuppressionRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
