// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kevin/vigil/ent/webhookdelivery"
)

// WebhookDelivery is the model entity for the WebhookDelivery schema.
type WebhookDelivery struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 目标订阅 URL
	URL string `json:"url,omitempty"`
	// 事件名，如 incident.created
	Event string `json:"event,omitempty"`
	// 关联 incident id（冗余，非外键）
	IncidentID int `json:"incident_id,omitempty"`
	// 出站请求体全量（重放原样重发）
	Payload []byte `json:"payload,omitempty"`
	// 投递终态：success 已送达 / failed 死信可重放
	Status webhookdelivery.Status `json:"status,omitempty"`
	// 累计投递尝试次数
	Attempts int `json:"attempts,omitempty"`
	// 最后失败原因（success 时为空）
	LastError string `json:"last_error,omitempty"`
	// 最后响应状态码，0=连接失败
	LastStatusCode int `json:"last_status_code,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebhookDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webhookdelivery.FieldPayload:
			values[i] = new([]byte)
		case webhookdelivery.FieldID, webhookdelivery.FieldIncidentID, webhookdelivery.FieldAttempts, webhookdelivery.FieldLastStatusCode:
			values[i] = new(sql.NullInt64)
		case webhookdelivery.FieldURL, webhookdelivery.FieldEvent, webhookdelivery.FieldStatus, webhookdelivery.FieldLastError:
			values[i] = new(sql.NullString)
		case webhookdelivery.FieldCreatedAt, webhookdelivery.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebhookDelivery fields.
func (_m *WebhookDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webhookdelivery.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case webhookdelivery.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case webhookdelivery.FieldEvent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event", values[i])
			} else if value.Valid {
				_m.Event = value.String
			}
		case webhookdelivery.FieldIncidentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field incident_id", values[i])
			} else if value.Valid {
				_m.IncidentID = int(value.Int64)
			}
		case webhookdelivery.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil {
				_m.Payload = *value
			}
		case webhookdelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = webhookdelivery.Status(value.String)
			}
		case webhookdelivery.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case webhookdelivery.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case webhookdelivery.FieldLastStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_status_code", values[i])
			} else if value.Valid {
				_m.LastStatusCode = int(value.Int64)
			}
		case webhookdelivery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case webhookdelivery.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebhookDelivery.
// This includes values selected through modifiers, order, etc.
func (_m *WebhookDelivery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WebhookDelivery.
// Note that you need to call WebhookDelivery.Unwrap() before calling this method if this WebhookDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WebhookDelivery) Update() *WebhookDeliveryUpdateOne {
	return NewWebhookDeliveryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WebhookDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WebhookDelivery) Unwrap() *WebhookDelivery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WebhookDelivery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WebhookDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("WebhookDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("event=")
	builder.WriteString(_m.Event)
	builder.WriteString(", ")
	builder.WriteString("incident_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.IncidentID))
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("last_status_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastStatusCode))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WebhookDeliveries is a parsable slice of WebhookDelivery.
type WebhookDeliveries []*WebhookDelivery
