// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevin/vigil/ent/predicate"
	"github.com/kevin/vigil/ent/webhooksubscription"
)

// WebhookSubscriptionDelete is the builder for deleting a WebhookSubscription entity.
type WebhookSubscriptionDelete struct {
	config
	hooks    []Hook
	mutation *WebhookSubscriptionMutation
}

// Where appends a list predicates to the WebhookSubscriptionDelete builder.
func (_d *WebhookSubscriptionDelete) Where(ps ...predicate.WebhookSubscription) *WebhookSubscriptionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WebhookSubscriptionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WebhookSubscriptionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WebhookSubscriptionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(webhooksubscription.Table, sqlgraph.NewFieldSpec(webhooksubscription.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WebhookSubscriptionDeleteOne is the builder for deleting a single WebhookSubscription entity.
type WebhookSubscriptionDeleteOne struct {
	_d *WebhookSubscriptionDelete
}

// Where appends a list predicates to the WebhookSubscriptionDelete builder.
func (_d *WebhookSubscriptionDeleteOne) Where(ps ...predicate.WebhookSubscription) *WebhookSubscriptionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WebhookSubscriptionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{webhooksubscription.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WebhookSubscriptionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
